const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const AREAS=["الكل","عبدون","أم أذينة","الرابية","خلدا","دير غبار","دابوق","الصويفية","وادي السير","بيادر وادي السير","أم السماق","تلاع العلي","الشميساني","جبل عمان","العبدلي","مرج الحمام","شارع مكة","الدوار الأول","الدوار الثاني","الدوار الثالث","الدوار الرابع","الدوار الخامس","الدوار السادس"];
const seedImages=["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85"];
const defaults={areas:AREAS.slice(1),whatsapp:"",notificationDays:7,heroTitle:"إدارة عقاراتك بسهولة واحترافية",heroSubtitle:"نظام متكامل لإدارة الشقق والمستأجرين في غرب عمان",theme:"dark",searchHistory:[]};
const state={user:null,token:"",properties:[],users:[],settings:{...defaults},filter:{q:"",area:"الكل",status:"الكل",rooms:"الكل",baths:"الكل",balcony:"الكل",minPrice:"",maxPrice:"",sort:"newest"},page:"home"};
function esc(v=""){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function toast(msg,good=true){const r=$("#toast-root");if(!r){alert(msg);return}const e=document.createElement("div");e.className="toast "+(good?"good":"bad");e.textContent=msg;r.appendChild(e);setTimeout(()=>e.remove(),3000)}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),...(state.token?{"Authorization":"Bearer "+state.token}:{})};const r=await fetch(url,opt);const x=await r.json().catch(()=>({}));if(!r.ok)throw Error(x.message||x.error||"حدث خطأ");return x}
function areas(){return state.settings.areas?.length?["الكل",...state.settings.areas]:AREAS}
function saveLocal(){localStorage.setItem("wam_settings",JSON.stringify(state.settings));localStorage.setItem("wam_filter",JSON.stringify(state.filter))}
function loadLocal(){try{state.settings={...defaults,...JSON.parse(localStorage.getItem("wam_settings")||"{}")};state.filter={...state.filter,...JSON.parse(localStorage.getItem("wam_filter")||"{}")}}catch{}}
async function loadPublic(){try{state.properties=await api("/api/public/properties")}catch(e){state.properties=[]}render()}
async function loadAdmin(){state.properties=await api("/api/properties");try{state.users=await api("/api/users")}catch{}render()}
async function loadState(){try{const d=await api("/api/state");const s=d.state||{};if(s.settings)state.settings={...state.settings,...s.settings};if(Array.isArray(s.searchHistory))state.settings.searchHistory=s.searchHistory;if(Array.isArray(s.areas))state.settings.areas=s.areas}catch{}}
function statusClass(s){return s==="متاحة"?"green":s==="مؤجرة"?"blue":s==="محجوزة"?"orange":"red"}
function filtered(){let p=[...state.properties],f=state.filter;if(f.q){const q=f.q.toLowerCase();p=p.filter(x=>`${x.name} ${x.code} ${x.area} ${x.notes||""}`.toLowerCase().includes(q))}if(f.area!=="الكل")p=p.filter(x=>x.area===f.area);if(f.status!=="الكل")p=p.filter(x=>x.status===f.status);if(f.rooms!=="الكل")p=p.filter(x=>String(x.rooms)===f.rooms);if(f.baths!=="الكل")p=p.filter(x=>String(x.baths)===f.baths);if(f.balcony!=="الكل")p=p.filter(x=>String(!!x.balcony)===(f.balcony==="1"));if(f.minPrice!=="")p=p.filter(x=>Number(x.price)>=Number(f.minPrice));if(f.maxPrice!=="")p=p.filter(x=>Number(x.price)<=Number(f.maxPrice));if(f.sort==="priceAsc")p.sort((a,b)=>a.price-b.price);if(f.sort==="priceDesc")p.sort((a,b)=>b.price-a.price);return p}
function filters(){const f=state.filter;return `<form id="searchForm" class="filters">
<div class="field search"><label>بحث</label><input id="q" value="${esc(f.q)}" placeholder="الكود أو الاسم أو المنطقة"></div>
<div class="field"><label>المنطقة</label><select id="area">${areas().map(x=>`<option ${x===f.area?"selected":""}>${esc(x)}</option>`).join("")}</select></div>
<div class="field"><label>الحالة</label><select id="status">${["الكل","متاحة","مؤجرة","محجوزة","قريبة من الانتهاء"].map(x=>`<option ${x===f.status?"selected":""}>${x}</option>`).join("")}</select></div>
<div class="field"><label>الغرف</label><select id="rooms">${["الكل","1","2","3","4","5","6"].map(x=>`<option ${x===f.rooms?"selected":""}>${x}</option>`).join("")}</select></div>
<div class="field"><label>الحمامات</label><select id="baths">${["الكل","1","2","3","4","5"].map(x=>`<option ${x===f.baths?"selected":""}>${x}</option>`).join("")}</select></div>
<div class="field"><label>بلكونة</label><select id="balcony"><option value="الكل">الكل</option><option value="1" ${f.balcony==="1"?"selected":""}>نعم</option><option value="0" ${f.balcony==="0"?"selected":""}>لا</option></select></div>
<div class="field"><label>السعر من</label><input id="minPrice" type="number" value="${esc(f.minPrice)}"></div><div class="field"><label>السعر إلى</label><input id="maxPrice" type="number" value="${esc(f.maxPrice)}"></div>
<div class="field"><label>الترتيب</label><select id="sort"><option value="newest">الأحدث</option><option value="priceAsc">الأقل سعراً</option><option value="priceDesc">الأعلى سعراً</option></select></div>
<button class="btn">🔍 بحث</button></form>`}
function cards(list){if(!list.length)return `<div class="empty">لا توجد شقق مطابقة للبحث.</div>`;return `<div class="cards">${list.map(p=>`<article class="card"><div class="card-media"><img src="${esc(p.images?.[0]||seedImages[0])}" alt="${esc(p.name)}"><span class="badge ${statusClass(p.status)}">${esc(p.status)}</span><span class="photo-count">📷 ${p.images?.length||0}</span></div><div class="card-body"><h3>${esc(p.name)}</h3><div class="muted">#${esc(p.code)} • ${esc(p.area)}</div><div class="card-meta"><span>🛏 ${p.rooms||0}</span><span>🛁 ${p.baths||0}</span><span>🌿 ${p.balcony?"نعم":"لا"}</span><span>₪ ${Number(p.price||0).toLocaleString("ar-JO")}</span></div><div class="card-actions"><button class="ghost-btn" data-view="${p.id}">التفاصيل</button>${state.user?`<button class="ghost-btn danger" data-delete="${p.id}">حذف</button>`:""}</div></div></article>`).join("")}</div>`}
function header(){return `<header class="topbar"><button class="menu-btn" id="menuBtn">☰</button><div class="brand"><div class="brand-mark">⌂</div><div>عقارات غرب عمان<small>${state.user?"لوحة الإدارة":"العقارات المتاحة"}</small></div></div><div class="top-actions">${state.user?`<button class="ghost-btn" id="logout">خروج</button>`:`<button class="ghost-btn" id="loginBtn">🔐 دخول المالك / المدير</button>`}</div></header>`}
function landing(){const soon=state.properties.filter(p=>p.availability_date&&p.status!=="متاحة").filter(p=>{const d=(new Date(p.availability_date)-new Date())/86400000;return d>=0&&d<=Number(state.settings.notificationDays||7)});return `${header()}<main class="content">
<section class="hero"><div class="hero-content"><div class="eyebrow">♛ عقارات غرب عمان</div><h1>${esc(state.settings.heroTitle)}</h1><p>${esc(state.settings.heroSubtitle)}</p><div class="hero-actions"><button class="btn" id="showProperties">استعراض العقارات</button><button class="ghost-btn" id="loginHero">دخول الإدارة</button></div></div></section>
${soon.length?`<div class="horizontal-strip alert-strip" id="soonStrip">🔴 ${soon.length} شقة ستصبح متاحة قريباً — اضغط لعرض القائمة</div>`:""}
${state.settings.searchHistory?.length?`<div class="horizontal-strip history-strip"><b>آخر عمليات البحث:</b>${state.settings.searchHistory.slice(0,8).map((h,i)=>`<button class="history-chip" data-history="${i}">${esc(h.label)}</button>`).join("")}</div>`:""}
<section class="panel landing-search"><div class="panel-title"><h2>🔎 البحث عن شقة</h2><span class="muted">${filtered().length} نتيجة</span></div>${filters()}<div id="landingResults">${cards(filtered())}</div></section></main>`}
function adminShell(){const items=[["dashboard","⌂","الرئيسية"],["properties","▦","الشقق"],["reports","▥","التقارير"],["settings","⚙","الإعدادات"],["admins","♙","إدارة المديرين"],["messages","✉","المحادثات"]];return `${header()}<div class="layout"><aside class="sidebar" id="sidebar"><div class="side-title">لوحة التحكم</div>${items.filter(x=>state.user.role==="owner"||state.user.permissions?.includes(x[0])).map(x=>`<button class="nav-item ${state.page===x[0]?"active":""}" data-page="${x[0]}"><span>${x[1]}</span>${x[2]}</button>`).join("")}<div class="side-footer"><b>${esc(state.user.name)}</b><br>${state.user.role==="owner"?"المالك":"مدير النظام"}</div></aside><main class="content">${pageContent()}</main></div>`}
function pageContent(){if(state.page==="dashboard")return dashboard();if(state.page==="properties")return propertyPage();if(state.page==="reports")return reports();if(state.page==="settings")return settingsPage();if(state.page==="admins")return adminsPage();return messagesPage()}
function dashboard(){const a=state.properties;return `<section class="panel"><div class="panel-title"><div><h2>لوحة التحكم</h2><div class="muted">نظرة سريعة على العقارات</div></div><button class="btn" id="newProperty">+ إضافة شقة</button></div><div class="stats"><div class="stat green"><span>متاحة</span><b>${a.filter(x=>x.status==="متاحة").length}</b></div><div class="stat blue"><span>مؤجرة</span><b>${a.filter(x=>x.status==="مؤجرة").length}</b></div><div class="stat orange"><span>محجوزة</span><b>${a.filter(x=>x.status==="محجوزة").length}</b></div><div class="stat red"><span>الإجمالي</span><b>${a.length}</b></div></div></section>`}
function propertyPage(){return `<section class="panel"><div class="panel-title"><div><h2>إدارة الشقق</h2><div class="muted">الحفظ يتم في Supabase</div></div><button class="btn" id="newProperty">+ إضافة شقة</button></div>${filters()}${cards(filtered())}</section>`}
function reports(){const a=state.properties;return `<section class="panel"><div class="panel-title"><h2>التقارير والإحصائيات</h2><button class="btn" id="exportData">تصدير نسخة احتياطية</button></div><div class="stats"><div class="stat"><span>الإجمالي</span><b>${a.length}</b></div><div class="stat green"><span>متاحة</span><b>${a.filter(x=>x.status==="متاحة").length}</b></div><div class="stat blue"><span>مؤجرة</span><b>${a.filter(x=>x.status==="مؤجرة").length}</b></div><div class="stat orange"><span>متوسط السعر</span><b>${a.length?Math.round(a.reduce((s,x)=>s+Number(x.price||0),0)/a.length):0}</b></div></div></section>`}
function settingsPage(){return `<section class="panel"><div class="panel-title"><h2>الإعدادات</h2></div><div class="settings-grid">
<div class="setting-card"><h3>المظهر</h3><label>التصميم</label><select id="setTheme"><option value="dark" ${state.settings.theme==="dark"?"selected":""}>الفخم الداكن</option><option value="light" ${state.settings.theme==="light"?"selected":""}>الفاتح</option></select><label>عنوان الصفحة</label><input id="setTitle" value="${esc(state.settings.heroTitle)}"><label>الوصف</label><input id="setSubtitle" value="${esc(state.settings.heroSubtitle)}"></div>
<div class="setting-card"><h3>تنبيهات التوفر</h3><label>عدد الأيام قبل التوفر</label><input id="setDays" type="number" min="0" value="${Number(state.settings.notificationDays||7)}"><label>رقم واتساب</label><input id="setWhatsapp" value="${esc(state.settings.whatsapp||"")}"></div>
<div class="setting-card full"><h3>المناطق</h3><div class="area-list">${(state.settings.areas||[]).map(a=>`<span>${esc(a)} <button class="mini danger" data-remove-area="${esc(a)}">×</button></span>`).join("")}</div><div class="inline"><input id="newAreaName" placeholder="اسم المنطقة الجديدة"><button class="btn" id="addArea">إضافة منطقة</button></div></div>
<div class="setting-card full"><h3>تغيير كلمة سر المالك</h3><div class="form-grid"><input id="ownerCurrent" type="password" placeholder="كلمة السر الحالية"><input id="ownerNew" type="password" placeholder="كلمة السر الجديدة"><button class="btn" id="changeOwnerPassword">حفظ كلمة السر الجديدة</button></div></div>
<div class="full"><button class="btn" id="saveSettings">حفظ جميع الإعدادات</button></div></div></section>`}
async function adminsPage(){let users=state.users;try{users=await api("/api/users")}catch{}return `<section class="panel"><div class="panel-title"><div><h2>إدارة المديرين</h2><div class="muted">صلاحيات المديرين وكلمات المرور</div></div><button class="btn" id="newAdmin">+ إضافة مدير</button></div><div class="table-wrap"><table class="table"><thead><tr><th>الاسم</th><th>البريد</th><th>الدور</th><th>الإجراء</th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${u.role==="owner"?"المالك":"مدير"}</td><td>${u.role==="admin"?`<button class="ghost-btn" data-password="${u.id}">تغيير كلمة السر</button>`:"-"}</td></tr>`).join("")}</tbody></table></div><div class="setting-card full" style="margin-top:18px"><h3>تغيير كلمة سر المالك</h3><div class="muted">هذا الخيار يظهر داخل صفحة إدارة المديرين للمالك فقط.</div><div class="form-grid"><input id="ownerCurrent" type="password" placeholder="كلمة السر الحالية"><input id="ownerNew" type="password" placeholder="كلمة السر الجديدة"><button class="btn" id="changeOwnerPassword">حفظ كلمة السر الجديدة</button></div></div></section>`}
function messagesPage(){return `<section class="panel"><div class="panel-title"><h2>المحادثات</h2></div><div class="empty">قسم المحادثات جاهز للربط والتوسعة.</div></section>`}
function modal(html){$("#modal-root")?.remove();const r=document.createElement("div");r.id="modal-root";r.innerHTML=`<div class="modal"><div class="modal-box">${html}</div></div>`;document.body.appendChild(r);$(".closeModal",r)?.addEventListener("click",()=>r.remove())}
function details(p){modal(`<div class="modal-head"><h2>${esc(p.name)}</h2><button class="icon-btn closeModal">✕</button></div><div class="muted">#${esc(p.code)} • ${esc(p.area)}</div><div class="details-gallery">${(p.images||[]).map(x=>`<img src="${esc(x)}">`).join("")||"<div class='empty'>لا توجد صور محفوظة.</div>"}</div><div class="detail-grid"><div><b>الغرف</b><span>${p.rooms||0}</span></div><div><b>الحمامات</b><span>${p.baths||0}</span></div><div><b>البلكونة</b><span>${p.balcony?"نعم":"لا"}</span></div><div><b>الطابق</b><span>${p.floor??"-"}</span></div><div><b>المساحة</b><span>${p.area_size?p.area_size+" م²":"-"}</span></div><div><b>السعر</b><span>${Number(p.price||0).toLocaleString("ar-JO")} دينار</span></div><div><b>الحالة</b><span class="badge ${statusClass(p.status)}">${esc(p.status)}</span></div></div><div class="copy-box"><label>التفاصيل الكاملة</label><textarea rows="7" readonly>🏠 عقارات غرب عمان
🔑 كود الشقة: ${p.code}
📍 المنطقة: ${p.area}
🛏️ الغرف: ${p.rooms||0}
🛁 الحمامات: ${p.baths||0}
🌿 بلكونة: ${p.balcony?"نعم":"لا"}
💰 السعر: ${p.price||0} دينار</textarea></div><div class="btn-row">${state.user?`<button class="btn" id="editProperty">تعديل</button>`:""}<button class="ghost-btn closeModal">إغلاق</button></div>`);$("#editProperty")?.addEventListener("click",()=>propertyForm(p))}
async function uploadImages(files){const fd=new FormData();for(const f of [...files].slice(0,30)){if(!["image/jpeg","image/png","image/webp"].includes(f.type))continue;if(f.size>8*1024*1024)throw Error("حجم الصورة يجب أن يكون أقل من 8MB.");fd.append("images",f)}const d=await api("/api/upload",{method:"POST",body:fd});if(!d.ok)throw Error(d.message||"فشل رفع الصور");return d.urls||[]}
function propertyForm(p=null){let imgs=[...(p?.images||[])];modal(`<div class="modal-head"><h2>${p?"تعديل الشقة":"إضافة شقة"}</h2><button class="icon-btn closeModal">✕</button></div><form id="propertyForm" class="form-grid">
<div class="field"><label>الكود</label><input id="code" required value="${esc(p?.code||"")}"></div><div class="field"><label>اسم الشقة</label><input id="name" required value="${esc(p?.name||"")}"></div>
<div class="field"><label>المنطقة</label><select id="area">${areas().filter(x=>x!=="الكل").map(x=>`<option ${x===p?.area?"selected":""}>${esc(x)}</option>`).join("")}</select></div><div class="field"><label>الحالة</label><select id="status">${["متاحة","مؤجرة","محجوزة","قريبة من الانتهاء"].map(x=>`<option ${x===(p?.status||"متاحة")?"selected":""}>${x}</option>`).join("")}</select></div>
<div class="field"><label>الغرف</label><input id="rooms" type="number" min="0" value="${p?.rooms||0}"></div><div class="field"><label>الحمامات</label><input id="baths" type="number" min="0" value="${p?.baths||0}"></div><div class="field"><label>البلكونة</label><select id="balcony"><option value="1" ${p?.balcony?"selected":""}>نعم</option><option value="0" ${!p?.balcony?"selected":""}>لا</option></select></div><div class="field"><label>الطابق</label><input id="floor" type="number" value="${p?.floor??""}"></div><div class="field"><label>المساحة م²</label><input id="areaSize" type="number" value="${p?.area_size??""}"></div><div class="field"><label>السعر الشهري</label><input id="price" type="number" value="${p?.price??""}"></div><div class="field"><label>تاريخ التوفر</label><input id="availability" type="date" value="${esc(p?.availability_date||"")}"></div><div class="field"><label>رابط الفيديو</label><input id="video" value="${esc(p?.video_url||"")}"></div>
<div class="field full"><label>ملاحظات</label><textarea id="notes">${esc(p?.notes||"")}</textarea></div>
<div class="field full"><label>الصور JPG / PNG / WEBP — حتى 30 صورة</label><input id="images" type="file" accept="image/jpeg,image/png,image/webp" multiple><div class="photos" id="previews">${imgs.map(x=>`<div class="photo"><img src="${esc(x)}"></div>`).join("")}</div></div>
<div class="full btn-row"><button class="btn">حفظ الشقة</button><button type="button" class="ghost-btn closeModal">إلغاء</button></div></form>`);
$("#images").onchange=async e=>{try{const urls=await uploadImages(e.target.files);imgs=[...imgs,...urls].slice(0,30);$("#previews").innerHTML=imgs.map(x=>`<div class="photo"><img src="${esc(x)}"></div>`).join("");toast("تم رفع الصور وحفظ روابطها");e.target.value=""}catch(err){toast(err.message,false)}};
$("#propertyForm").onsubmit=async e=>{e.preventDefault();try{const body={code:$("#code").value.trim(),name:$("#name").value.trim(),area:$("#area").value,status:$("#status").value,rooms:Number($("#rooms").value||0),baths:Number($("#baths").value||0),balcony:Number($("#balcony").value||0),floor:$("#floor").value===""?null:Number($("#floor").value),areaSize:$("#areaSize").value===""?null:Number($("#areaSize").value),price:Number($("#price").value||0),availabilityDate:$("#availability").value||null,video:$("#video").value.trim(),notes:$("#notes").value.trim(),images:imgs};await api(p?`/api/properties/${p.id}`:"/api/properties",{method:p?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});$("#modal-root")?.remove();await loadAdmin();toast("تم حفظ الشقة والصور بنجاح")}catch(err){toast(err.message,false)}}
}
function adminForm(){modal(`<div class="modal-head"><h2>إضافة مدير</h2><button class="icon-btn closeModal">✕</button></div><form id="adminForm" class="form-grid"><div class="field"><label>اسم المدير</label><input id="aname" required></div><div class="field"><label>البريد الإلكتروني</label><input id="aemail" type="email" required></div><div class="field"><label>كلمة المرور</label><input id="apass" type="password" minlength="6" required></div><div class="full"><b>الصلاحيات</b><div class="checks">${["dashboard","properties","reports","settings","messages"].map(x=>`<label><input type="checkbox" data-perm="${x}" checked> ${x==="dashboard"?"الرئيسية":x==="properties"?"الشقق":x==="reports"?"التقارير":x==="settings"?"الإعدادات":"المحادثات"}</label>`).join("")}</div></div><div class="full"><button class="btn">إنشاء المدير</button></div></form>`);$("#adminForm").onsubmit=async e=>{e.preventDefault();try{const permissions=$$("[data-perm]",$("#adminForm")).filter(x=>x.checked).map(x=>x.dataset.perm);await api("/api/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:$("#aname").value.trim(),email:$("#aemail").value.trim(),password:$("#apass").value,permissions})});$("#modal-root")?.remove();await loadAdmin();toast("تم إنشاء المدير") }catch(err){toast(err.message,false)}}}
function passwordForm(id){modal(`<div class="modal-head"><h2>تغيير كلمة سر المدير</h2><button class="icon-btn closeModal">✕</button></div><form id="pwForm" class="form-grid"><div class="field full"><label>كلمة السر الجديدة</label><input id="newPw" type="password" minlength="6" required></div><div class="full"><button class="btn">حفظ كلمة السر</button></div></form>`);$("#pwForm").onsubmit=async e=>{e.preventDefault();try{await api(`/api/users/${id}/password`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:$("#newPw").value})});$("#modal-root")?.remove();toast("تم تغيير كلمة سر المدير")}catch(err){toast(err.message,false)}}}
function saveSettings(){state.settings.heroTitle=$("#setTitle").value.trim();state.settings.heroSubtitle=$("#setSubtitle").value.trim();state.settings.notificationDays=Number($("#setDays").value||7);state.settings.whatsapp=$("#setWhatsapp").value.trim();state.settings.theme=$("#setTheme").value;saveLocal()}
function bind(){
$("#menuBtn")?.addEventListener("click",()=>$("#sidebar")?.classList.toggle("open"));
$("#loginBtn")?.addEventListener("click",()=>{state.page="login";render()});$("#loginHero")?.addEventListener("click",()=>{state.page="login";render()});
$("#logout")?.addEventListener("click",()=>{state.user=null;state.token="";localStorage.removeItem("wam_auth_token");localStorage.removeItem("wam_auth_user");state.page="home";loadPublic()});
$("#showProperties")?.addEventListener("click",()=>{$("#landingResults")?.scrollIntoView({behavior:"smooth"})});
$("#loginForm")?.addEventListener("submit",async e=>{e.preventDefault();try{const d=await api("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:$("#email").value.trim(),password:$("#password").value})});state.user=d.user;state.token=d.token;localStorage.setItem("wam_auth_token",d.token);localStorage.setItem("wam_auth_user",JSON.stringify(d.user));state.page="dashboard";await loadAdmin()}catch(err){toast(err.message,false)}});
$$("[data-page]").forEach(b=>b.onclick=()=>{state.page=b.dataset.page;$("#sidebar")?.classList.remove("open");render()});
$("#newProperty")?.addEventListener("click",()=>propertyForm());
$("#newAdmin")?.addEventListener("click",()=>adminForm());
$$("[data-view]").forEach(b=>b.onclick=()=>details(state.properties.find(p=>String(p.id)===String(b.dataset.view))));
$$("[data-delete]").forEach(b=>b.onclick=async()=>{if(!confirm("حذف الشقة؟"))return;try{await api(`/api/properties/${b.dataset.delete}`,{method:"DELETE"});await loadAdmin();toast("تم حذف الشقة")}catch(e){toast(e.message,false)}});
$$("[data-password]").forEach(b=>b.onclick=()=>passwordForm(b.dataset.password));
$("#searchForm")?.addEventListener("submit",e=>{e.preventDefault();state.filter={q:$("#q").value.trim(),area:$("#area").value,status:$("#status").value,rooms:$("#rooms").value,baths:$("#baths").value,balcony:$("#balcony").value,minPrice:$("#minPrice").value,maxPrice:$("#maxPrice").value,sort:$("#sort").value};if(state.page==="home"){const label=[state.filter.q&&`بحث: ${state.filter.q}`,state.filter.area!=="الكل"&&`المنطقة: ${state.filter.area}`,state.filter.status!=="الكل"&&`الحالة: ${state.filter.status}`].filter(Boolean).join(" • ");if(label){state.settings.searchHistory=[{label,...state.filter},...(state.settings.searchHistory||[]).filter(x=>x.label!==label)].slice(0,8);saveLocal()}render()}else loadAdmin()});
$$("[data-history]").forEach(b=>b.onclick=()=>{const h=state.settings.searchHistory[Number(b.dataset.history)];if(!h)return;state.filter={q:h.q||"",area:h.area||"الكل",status:h.status||"الكل",rooms:h.rooms||"الكل",baths:h.baths||"الكل",balcony:h.balcony||"الكل",minPrice:h.minPrice||"",maxPrice:h.maxPrice||"",sort:h.sort||"newest"};render()});
$("#saveSettings")?.addEventListener("click",async()=>{try{saveSettings();await api("/api/state",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({state:{settings:state.settings,areas:state.settings.areas,searchHistory:state.settings.searchHistory}})});render();toast("تم حفظ جميع الإعدادات")}catch(e){toast(e.message,false)}});
$("#addArea")?.addEventListener("click",async()=>{const n=$("#newAreaName").value.trim();if(!n)return toast("اكتب اسم المنطقة",false);if(!state.settings.areas.includes(n))state.settings.areas.push(n);saveLocal();render();toast("تمت إضافة المنطقة")});
$$("[data-remove-area]").forEach(b=>b.onclick=()=>{state.settings.areas=state.settings.areas.filter(x=>x!==b.dataset.removeArea);saveLocal();render()});
$("#changeOwnerPassword")?.addEventListener("click",async()=>{try{await api("/api/owner/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword:$("#ownerCurrent").value,newPassword:$("#ownerNew").value})});toast("تم تغيير كلمة سر المالك بنجاح");$("#ownerCurrent").value="";$("#ownerNew").value=""}catch(e){toast(e.message,false)}});
$("#exportData")?.addEventListener("click",()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify({version:"19.0.0",properties:state.properties,settings:state.settings},null,2)],{type:"application/json"}));a.download="west-amman-backup.json";a.click()});
}
function loginView(){return `<div class="login"><div class="login-box"><div class="brand"><div class="brand-mark">⌂</div><div>عقارات غرب عمان<small>WEST AMMAN PROPERTY MANAGER</small></div></div><h1>تسجيل الدخول</h1><p class="login-note">الدخول للمالك والمديرين فقط</p><form id="loginForm" class="login-form"><label>البريد الإلكتروني</label><input id="email" type="email" required><label>كلمة المرور</label><input id="password" type="password" required><button class="btn">دخول إلى النظام</button><button type="button" class="ghost-btn" id="backHome">العودة</button></form></div></div>`}
function render(){document.body.className=state.settings.theme==="light"?"light":"";const root=$("#app");if(state.page==="login"){root.innerHTML=loginView();$("#backHome").onclick=()=>{state.page="home";loadPublic()};bind();return}root.innerHTML=state.user?adminShell():landing();bind()}
(async()=>{loadLocal();try{const t=localStorage.getItem("wam_auth_token"),u=JSON.parse(localStorage.getItem("wam_auth_user")||"null");if(t&&u){state.token=t;state.user=u;await loadState();state.page="dashboard";await loadAdmin();return}await loadState()}catch{}loadPublic()})();