
function v511Price(a,rt){if(rt==='يومي')return Number(a.daily_rent||0);if(rt==='سنوي')return Number(a.annual_rent||0);return Number(a.monthly_rent||a.rent||0)}
function v511OpenPriceRange(){
  const box=document.createElement('div'); box.className='wa-picker';
  box.innerHTML=`<div class="wa-picker-box"><div class="modalhead"><h3>🔎 بحث الشقق حسب السعر</h3><button class="btn ghost" id="v511RangeClose">إغلاق</button></div><div class="notice">حدد السعر من وإلى، وسيتم تطبيق البحث على نوع الإيجار المختار.</div><div class="formgrid"><div class="field"><label>من سعر</label><input id="v511Min" type="number" min="0" value="${window.v511Min??''}"></div><div class="field"><label>إلى سعر</label><input id="v511Max" type="number" min="0" value="${window.v511Max??''}"></div></div><div class="wa-range-actions"><button class="btn ghost" id="v511RangeClear">مسح السعر</button><button class="btn primary" id="v511RangeApply">تطبيق البحث</button></div></div>`;
  document.body.appendChild(box);
  box.querySelector('#v511RangeClose').onclick=()=>box.remove();
  box.querySelector('#v511RangeClear').onclick=()=>{window.v511Min='';window.v511Max='';box.remove();drawA()};
  box.querySelector('#v511RangeApply').onclick=()=>{let mn=Number(box.querySelector('#v511Min').value||0),mx=Number(box.querySelector('#v511Max').value||0);if(mn&&mx&&mn>mx){alert('السعر الأدنى لا يمكن أن يكون أكبر من السعر الأعلى');return}window.v511Min=mn||'';window.v511Max=mx||'';box.remove();drawA()};
  box.onclick=e=>{if(e.target===box)box.remove()};
}
function apartments(){return `<div class="panel"><div class="head"><h3>إدارة العقارات</h3>${me.role!=="user"?'<button class="btn primary" onclick="addA()">＋ إضافة شقة</button>':''}</div><div class="toolbar v59-search"><input id="aq" placeholder="بحث برقم الشقة أو المنطقة..." oninput="drawA()"><select id="arooms" onchange="drawA()"><option value="">كل الغرف</option><option value="1">1 غرفة</option><option value="2">2 غرف</option><option value="3">3 غرف</option><option value="4">4 غرف</option></select><select id="art" onchange="drawA()"><option value="">كل أنواع الإيجار</option><option>يومي</option><option>شهري</option><option>سنوي</option></select><select id="af" onchange="drawA()"><option value="">كل المناطق</option>${D.areas.map(a=>`<option>${esc(a.name)}</option>`).join('')}</select><select id="as" onchange="drawA()"><option value="">كل الحالات</option>${statuses.map(s=>`<option>${s}</option>`).join('')}</select><button class="btn primary" onclick="v511OpenPriceRange()">💰 بحث من سعر إلى سعر</button><button class="btn ghost" onclick="resetApartmentSearch()">مسح البحث</button><button class="btn ghost" onclick="location.href='/api/export/apartments.csv'">تصدير CSV</button></div><div class="notice" style="margin-top:10px">بحث السعر يتم حسب النوع المختار: يومي أو شهري أو سنوي.</div><div id="alist" class="cards" style="margin-top:16px"></div></div>`}
function drawA(){let q=($('aq')?.value||'').toLowerCase(),ar=$('af')?.value||'',st=$('as')?.value||'',rt=$('art')?.value||'',rooms=Number($('arooms')?.value||0),min=Number(window.v511Min||0),max=Number(window.v511Max||0);let x=D.apartments.filter(a=>{let p=v511Price(a,rt);return (a.number+' '+a.area).toLowerCase().includes(q)&&(!ar||a.area===ar)&&(!st||a.status===st)&&(!rt||a.rental_type===rt)&&(!rooms||Number(a.rooms||0)===rooms)&&(!min||p>=min)&&(!max||p<=max)});$('alist').innerHTML=x.length?x.map(card).join(''):'<div class="empty">لا توجد نتائج</div>'}
function resetApartmentSearch(){['aq','arooms','art','af','as'].forEach(id=>{if($(id))$(id).value=''});window.v511Min='';window.v511Max='';drawA()}
function v511WaShare(files,title){return navigator.share&&navigator.canShare&&navigator.canShare({files})?navigator.share({title,files}):Promise.reject(new Error('افتح التطبيق من Chrome على الهاتف لاستخدام مشاركة WhatsApp للصور أو الفيديو.'))}
function waDetailsButton(id){return `<button class="btn wa-btn" onclick="shareApartmentDetails(${id})">🟢 واتساب</button>`}
async function shareApartmentPhotos(id){
  if(me?.role!=='owner'){alert('المشاركة متاحة للمالك فقط');return}
  const photos=D.documents.filter(d=>d.apartment_id===id&&d.kind==='صورة شقة'); if(!photos.length){alert('لا توجد صور لهذه الشقة');return}
  const box=document.createElement('div');box.className='wa-picker';
  box.innerHTML=`<div class="wa-picker-box"><div class="modalhead"><h3>🟢 إرسال الصور عبر WhatsApp</h3><button class="btn ghost" id="waClose">إغلاق</button></div><div class="notice">حدد عدد الصور التي تريد إرسالها، ثم اضغط WhatsApp. سيظهر WhatsApp ضمن قائمة المشاركة في الهاتف.</div><div class="wa-photo-list">${photos.map((p,i)=>`<label class="wa-photo-item"><input type="checkbox" data-i="${i}"><img src="/uploads/${encodeURIComponent(p.filename)}" alt="صورة ${i+1}"></label>`).join('')}</div><div class="wa-range-actions"><button class="btn ghost" id="waAll">تحديد الكل</button><button class="btn wa-btn" id="waSend">🟢 WhatsApp — إرسال الصور</button></div></div>`;
  document.body.appendChild(box);box.querySelector('#waClose').onclick=()=>box.remove();box.onclick=e=>{if(e.target===box)box.remove()};
  box.querySelectorAll('.wa-photo-item').forEach(el=>{el.onclick=e=>{if(e.target.tagName!=='INPUT'){const cb=el.querySelector('input');cb.checked=!cb.checked}el.classList.toggle('selected',el.querySelector('input').checked)}});
  box.querySelector('#waAll').onclick=()=>box.querySelectorAll('input[type=checkbox]').forEach(cb=>{cb.checked=true;cb.closest('.wa-photo-item').classList.add('selected')});
  box.querySelector('#waSend').onclick=async()=>{try{const chosen=[...box.querySelectorAll('input[type=checkbox]:checked')].map(cb=>photos[Number(cb.dataset.i)]);if(!chosen.length){alert('حدد صورة واحدة على الأقل');return}const files=[];for(const d of chosen){const r=await fetch('/uploads/'+encodeURIComponent(d.filename));if(r.ok){const b=await r.blob();files.push(new File([b],d.original_name||d.filename,{type:b.type||'image/jpeg'}))}}if(!files.length)throw Error('تعذر تجهيز الصور');await v511WaShare(files,'صور الشقة');box.remove()}catch(e){if(e?.name!=='AbortError')alert(e.message||'تعذر مشاركة الصور')}};
}
async function shareApartmentVideo(id){
  if(me?.role!=='owner'){alert('المشاركة متاحة للمالك فقط');return}
  const a=D.apartments.find(x=>x.id===id),d=D.documents.find(x=>x.apartment_id===id&&x.kind==='فيديو شقة');if(!a||!d){alert('لا يوجد فيديو لهذه الشقة');return}
  try{const r=await fetch('/uploads/'+encodeURIComponent(d.filename));if(!r.ok)throw Error('تعذر تجهيز الفيديو');const b=await r.blob();const file=new File([b],d.original_name||`فيديو-شقة-${a.number}.mp4`,{type:b.type||'video/mp4'});await v511WaShare([file],`فيديو شقة ${a.number}`)}catch(e){if(e?.name!=='AbortError')alert(e.message||'تعذر مشاركة الفيديو')}
}
function videoHtml(d){return `<div class="video-wrap v55-video-card" onclick="openMiniVideo(${d.apartment_id})"><div class="v55-video-play-label">▶ تشغيل داخل التطبيق</div><video class="v55-video-thumb" muted playsinline preload="metadata" src="/uploads/${encodeURIComponent(d.filename)}"></video><div class="row" onclick="event.stopPropagation()"><span class="muted">🎥 ${esc(d.original_name)}</span><div class="v510-video-actions"><button class="btn ghost" onclick="openMiniVideo(${d.apartment_id})">▶ تشغيل</button>${me.role==='owner'?`<button class="btn wa-btn" onclick="shareApartmentVideo(${d.apartment_id})">🟢 WhatsApp — إرسال الفيديو</button><button class="btn v510-video-download" onclick="downloadApartmentVideo(${d.id})">⬇ تحميل</button>`:''}${me.role!=='user'?`<button class="btn danger" onclick="deleteVideo(${d.id},${d.apartment_id})">حذف</button>`:''}</div></div></div>`}
async function shareApartmentDetails(id){
  if(me?.role!=='owner'){alert('المشاركة متاحة للمالك فقط');return}
  const a=D.apartments.find(x=>x.id===id);if(!a)throw Error('الشقة غير موجودة');
  const rows=[['الكود',a.code||a.number||'—'],['رقم الشقة',a.number||'—'],['المنطقة',a.area||'—'],['الحالة',a.status||'—'],['الغرف',a.rooms||0],['الحمامات',a.baths||0],['الصالات',a.living_rooms||0],['الصالونات',a.salons||0],['البلكونات',a.balconies||0],['المساحة',`${a.size_m2||0} م²`],['الطابق',a.floor||0],['نوع الإيجار',a.rental_type||'—'],['الإيجار اليومي',`${v58Price(a.daily_rent)} د.أ`],['الإيجار الشهري',`${v58Price(a.monthly_rent||a.rent)} د.أ`],['الإيجار السنوي',`${v58Price(a.annual_rent)} د.أ`],['موعد التوفر',a.available_date||'غير محدد'],['التنبيه قبل التوفر',`${a.availability_alert_days||0} يوم`],['الملاحظات',a.notes||'—']];
  const w=1200,rowH=68,h=170+rows.length*rowH;const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const c=canvas.getContext('2d');c.fillStyle='#f7f0e4';c.fillRect(0,0,w,h);c.fillStyle='#251432';c.roundRect(35,30,w-70,105,24);c.fill();c.fillStyle='#f1d486';c.font='900 44px Tahoma';c.textAlign='right';c.direction='rtl';c.fillText(`تفاصيل الشقة — ${a.number||''}`,w-70,88);c.font='700 23px Tahoma';c.fillText(a.area||'',w-70,120);let y=180;rows.forEach(([k,v],i)=>{c.fillStyle=i%2?'#fffaf2':'#f1e8d9';c.roundRect(45,y-34,w-90,54,13);c.fill();c.fillStyle='#756b75';c.font='700 21px Tahoma';c.textAlign='right';c.fillText(k,w-80,y);c.fillStyle='#241c27';c.font='800 22px Tahoma';c.textAlign='left';c.fillText(String(v),80,y);y+=rowH});c.fillStyle='#6d6370';c.font='600 18px Tahoma';c.textAlign='right';c.fillText('إدارة عقارات غرب عمّان',w-70,h-18);const blob=await new Promise(r=>canvas.toBlob(r,'image/png',1));if(!blob)throw Error('تعذر إنشاء صورة التفاصيل');const file=new File([blob],`تفاصيل-الشقة-${a.number||id}.png`,{type:'image/png'});await v511WaShare([file],`تفاصيل شقة ${a.number||''}`)
}
function editA(id){let a=D.apartments.find(x=>x.id===id);let photos=D.documents.filter(d=>d.apartment_id===id&&d.kind==='صورة شقة');let videos=D.documents.filter(d=>d.apartment_id===id&&d.kind==='فيديو شقة');modal(`<div class="modalhead"><h3>تفاصيل الشقة ${esc(a.number)}</h3><button class="btn ghost" onclick="closeM()">✕ إغلاق</button></div>${aForm(a)}${me.role==='owner'?`<div class="v55-share-row"><button class="btn wa-btn" onclick="shareApartmentDetails(${id})">🟢 WhatsApp — التفاصيل كجدول</button></div>`:''}<div class="panel" style="margin-top:14px;padding:14px"><div class="head"><h3>📷 صور الشقة</h3><span class="muted">${photos.length} صورة</span></div>${me.role==='owner'&&photos.length?`<button class="btn wa-btn" onclick="shareApartmentPhotos(${id})">🟢 WhatsApp — تحديد الصور</button>`:''}${me.role!=='user'?`<input id="apPhotos" type="file" accept="image/jpeg,image/png,image/webp" multiple onchange="uploadApartmentPhotos(${id})">`:''}<div id="photos_${id}" class="photos">${photos.length?photos.map((p,i)=>photoHtml(p,i)).join(''):'<div class="photoempty full">لا توجد صور لهذه الشقة</div>'}</div></div><div class="panel" style="margin-top:14px;padding:14px"><div class="head"><h3>🎥 فيديو الشقة</h3><span class="muted">${videos.length} فيديو</span></div>${me.role!=='user'?`<label class="btn ghost" style="display:inline-flex;align-items:center;gap:6px">🎥 تحميل فيديو الشقة<input id="apVideo" type="file" accept="video/mp4,video/webm,video/quicktime,video/x-m4v" onchange="uploadApartmentVideo(${id})" style="display:none"></label>`:''}${videos.length?videos.map(videoHtml).join(''):'<div class="photoempty">لا يوجد فيديو لهذه الشقة</div>'}</div><div style="display:flex;gap:8px;margin-top:14px;flex-wrap:wrap"><button class="btn primary" onclick="saveA(${id})">حفظ التعديل</button>${me.role==='owner'?`<button class="btn danger" onclick="delA(${id})">حذف الشقة</button>`:''}</div>`)}
function tenants(){return `<div class="panel"><div class="head"><h3>المستأجرون والعقود</h3>${me.role!=="user"?'<button class="btn primary" onclick="addT()">＋ إضافة مستأجر</button>':''}</div><table><thead><tr><th>المستأجر</th><th>الشقة</th><th>الهاتف</th><th>الإيجار</th><th>بداية العقد</th><th>نهاية العقد</th><th>التجديد</th><th>الوثيقة</th></tr></thead><tbody>${D.tenants.map(t=>{let docs=D.documents.filter(d=>d.tenant_id===t.id&&d.kind==='هوية/جواز');return `<tr><td><b>${esc(t.name)}</b></td><td>${esc(t.apartment||'—')}</td><td>${esc(t.phone)}</td><td>${Number(t.monthly_rent||0).toLocaleString()}</td><td>${esc(t.contract_start||'—')}</td><td>${esc(t.contract_end||'—')}</td><td><span class="renew-toggle"><span class="renew-dot ${t.renewal_enabled?'on':'off'}"></span>${t.renewal_enabled?'مفعّل':'متوقف'}</span></td><td>${docs.length?`<span class="tenant-doc">📎 ${docs.length} ملف</span>`:'—'}</td></tr>`}).join('')||'<tr><td colspan="8" class="empty">لا يوجد مستأجرون</td></tr>'}</tbody></table></div>`}
function addT(){modal(`<div class="modalhead"><h3>إضافة مستأجر وعقد</h3><button class="btn ghost" onclick="closeM()">✕ إغلاق</button></div><div class="formgrid"><div class="field"><label>الاسم</label><input id="tn"></div><div class="field"><label>الهاتف</label><input id="tp"></div><div class="field"><label>رقم الهوية</label><input id="tid"></div><div class="field"><label>الشقة</label><select id="ta"><option value="">بدون</option>${D.apartments.map(a=>`<option value="${a.id}">${a.number} — ${a.area}</option>`).join('')}</select></div><div class="field"><label>بداية العقد</label><input id="cs" type="date"></div><div class="field"><label>نهاية العقد</label><input id="ce" type="date"></div><div class="field"><label>الإيجار الشهري</label><input id="tr" type="number"></div><div class="field"><label>التأمين</label><input id="dep" type="number"></div><div class="field full"><label>صورة الهوية أو جواز السفر</label><input id="tDoc" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"></div><div class="field full"><button type="button" class="renew-toggle" id="renewToggle"><span class="renew-dot on"></span><span>التجديد: مفعّل</span></button></div><div class="field full"><label>ملاحظات</label><textarea id="tnote"></textarea></div></div><button class="btn primary" style="margin-top:14px" onclick="saveT()">حفظ المستأجر</button>`);let b=$('renewToggle');b.dataset.enabled='1';b.onclick=()=>{let on=b.dataset.enabled==='1';b.dataset.enabled=on?'0':'1';b.innerHTML=`<span class="renew-dot ${on?'off':'on'}"></span><span>التجديد: ${on?'متوقف':'مفعّل'}</span>`}}
async function saveT(){try{const enabled=$('renewToggle')?.dataset.enabled!=='0';const j=await api('/api/tenants',{method:'POST',body:JSON.stringify({name:tn.value,phone:tp.value,national_id:tid.value,apartment_id:ta.value?+ta.value:null,contract_start:cs.value,contract_end:ce.value,monthly_rent:+tr.value,deposit:+dep.value,status:'نشط',renewal_enabled:enabled,notes:tnote.value})});const f=$('tDoc')?.files?.[0];if(f&&j.id){let fd=new FormData();fd.append('file',f);fd.append('tenant_id',j.id);fd.append('kind','هوية/جواز');let r=await fetch('/api/documents',{method:'POST',headers:{Authorization:'Bearer '+token},body:fd});let x=await r.json();if(!r.ok)throw Error(x.error||'تعذر رفع وثيقة الهوية')}closeM();await load();notify('تم حفظ المستأجر والوثيقة بنجاح')}catch(e){alert(e.message)}}
