
/* v5.13 authoritative final layer: intentionally last so no legacy script can override it. */
window.v511Min=window.v511Min||''; window.v511Max=window.v511Max||''; window.v59PriceSort='none';
function v511Price(a,rt){if(rt==='يومي')return Number(a.daily_rent||0);if(rt==='سنوي')return Number(a.annual_rent||0);return Number(a.monthly_rent||a.rent||0)}
function v511CanPrice(){return me?.role==='owner'}
function v511ShareFiles(files,title){
  if(!files.length) return Promise.reject(new Error('لا توجد ملفات للمشاركة'));
  if(!navigator.share||!navigator.canShare||!navigator.canShare({files})) return Promise.reject(new Error('افتح التطبيق في Chrome على الهاتف، ثم اختر WhatsApp من قائمة المشاركة.'));
  return navigator.share({title,files});
}
function v511PriceRange(){
 const box=document.createElement('div');box.className='wa-picker';
 box.innerHTML=`<div class="wa-picker-box"><div class="modalhead"><h3>🔎 بحث الشقق حسب السعر</h3><button class="btn ghost" id="rClose">إغلاق</button></div><div class="notice">حدد السعر من وإلى، وسيتم البحث حسب نوع الإيجار المختار.</div><div class="formgrid"><div class="field"><label>من سعر</label><input id="rMin" type="number" min="0" value="${window.v511Min||''}"></div><div class="field"><label>إلى سعر</label><input id="rMax" type="number" min="0" value="${window.v511Max||''}"></div></div><div class="wa-range-actions"><button class="btn ghost" id="rClear">مسح السعر</button><button class="btn primary" id="rApply">تطبيق البحث</button></div></div>`;
 document.body.appendChild(box);box.querySelector('#rClose').onclick=()=>box.remove();box.onclick=e=>{if(e.target===box)box.remove()};
 box.querySelector('#rClear').onclick=()=>{window.v511Min='';window.v511Max='';box.remove();drawA()};
 box.querySelector('#rApply').onclick=()=>{const mn=Number(box.querySelector('#rMin').value||0),mx=Number(box.querySelector('#rMax').value||0);if(mn&&mx&&mn>mx)return alert('من السعر لا يمكن أن يكون أكبر من إلى السعر');window.v511Min=mn||'';window.v511Max=mx||'';box.remove();drawA()};
}

function drawA(){const q=($('aq')?.value||'').toLowerCase(),ar=$('af')?.value||'',st=$('as')?.value||'',rt=$('art')?.value||'',rooms=Number($('arooms')?.value||0),mn=Number(window.v511Min||0),mx=Number(window.v511Max||0);let x=D.apartments.filter(a=>{const p=v511Price(a,rt);return (a.number+' '+a.area).toLowerCase().includes(q)&&(!ar||a.area===ar)&&(!st||a.status===st)&&(!rt||a.rental_type===rt)&&(!rooms||Number(a.rooms||0)===rooms)&&(!mn||p>=mn)&&(!mx||p<=mx)});$('alist').innerHTML=x.length?x.map(card).join(''):'<div class="empty">لا توجد نتائج</div>'}
function resetApartmentSearch(){['aq','arooms','art','af','as'].forEach(id=>{if($(id))$(id).value=''});window.v511Min='';window.v511Max='';drawA()}
function card(a){const photos=D.documents.filter(d=>d.apartment_id===a.id&&d.kind==='صورة شقة'),videos=D.documents.filter(d=>d.apartment_id===a.id&&d.kind==='فيديو شقة'),shown=photos.slice(0,6);const photoGrid=shown.length?`<div class="card-photo-grid">${shown.map((p,i)=>`<div class="card-photo" onclick="event.stopPropagation();openApartmentGallery(${a.id},${i})"><img src="/uploads/${encodeURIComponent(p.filename)}" alt="صورة الشقة ${i+1}">${i===5&&photos.length>6?`<span class="card-photo-more">+${photos.length-6}</span>`:''}</div>`).join('')}</div>`:`<div class="card-photo-empty">📷 لا توجد صور</div>`;const price=v511CanPrice()?`<br>💰 ${Number(v511Price(a,a.rental_type||'شهري')).toLocaleString()} د.أ / ${esc(a.rental_type||'شهري')}`:'';return `<div class="card" data-apartment-id="${a.id}">${photoGrid}<h4>شقة ${esc(a.number)}</h4><div class="meta"><b>${esc(a.area)}</b><br>${a.rooms||0} غرف • ${a.baths||0} حمام • ${a.size_m2||0} م²<br>طابق ${a.floor||0}${price}<br>📷 ${photos.length} صورة ${videos.length?` • 🎥 ${videos.length} فيديو`:''}</div><div class="row">${badge(a.status)}<button class="btn ghost" onclick="editA(${a.id})">التفاصيل</button></div></div>`}
function aForm(a={}){const rt=a.rental_type||'شهري';return `<div class="formgrid"><div class="field"><label>كود الشقة</label><input id="acode" value="${esc(a.code||a.number||'')}"></div><div class="field"><label>رقم الشقة</label><input id="an" value="${esc(a.number||'')}"></div><div class="field"><label>المنطقة</label><select id="aa">${D.areas.map(x=>`<option value="${x.id}" ${(x.id===a.area_id||x.name===a.area)?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>الحالة</label><select id="ast">${statuses.map(s=>`<option ${s===a.status?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>نوع الإيجار</label><select id="artype"><option ${rt==='يومي'?'selected':''}>يومي</option><option ${rt==='شهري'?'selected':''}>شهري</option><option ${rt==='سنوي'?'selected':''}>سنوي</option></select></div><div class="field"><label>المساحة (م²)</label><input id="az" type="number" value="${a.size_m2||0}"></div><div class="field"><label>الغرف</label><input id="ro" type="number" value="${a.rooms||0}"></div><div class="field"><label>الحمامات</label><input id="ba" type="number" value="${a.baths||0}"></div><div class="field"><label>الصالات</label><input id="lr" type="number" value="${a.living_rooms||0}"></div><div class="field"><label>الصالونات</label><input id="sal" type="number" value="${a.salons||0}"></div><div class="field"><label>البلكونات</label><input id="bal" type="number" value="${a.balconies||0}"></div><div class="field"><label>الطابق</label><input id="fl" type="number" value="${a.floor||1}"></div>${v511CanPrice()?`<div class="full v58-rent-grid"><div class="v58-price"><label>الإيجار اليومي</label><input id="rd" type="number" value="${a.daily_rent||0}"></div><div class="v58-price"><label>الإيجار الشهري</label><input id="rm" type="number" value="${a.monthly_rent||a.rent||0}"></div><div class="v58-price"><label>الإيجار السنوي</label><input id="ry" type="number" value="${a.annual_rent||0}"></div></div>`:`<input id="rd" type="hidden" value="${a.daily_rent||0}"><input id="rm" type="hidden" value="${a.monthly_rent||a.rent||0}"><input id="ry" type="hidden" value="${a.annual_rent||0}">`}<div class="field"><label>موعد التوفر</label><input id="avdate" type="date" value="${esc(a.available_date||'')}"></div><div class="field"><label>التنبيه قبل التوفر بعدد الأيام</label><input id="avdays" type="number" min="0" max="365" value="${a.availability_alert_days||0}"></div><div class="field"><label><input id="aven" type="checkbox" ${a.availability_alert_enabled?'checked':''}> تفعيل تنبيه قرب التوفر</label></div><div class="field full"><label>ملاحظات</label><textarea id="no">${esc(a.notes||'')}</textarea></div></div>`}
function addA(){modal(`<div class="modalhead"><h3>إضافة شقة جديدة</h3><button class="btn ghost" onclick="closeM()">إغلاق</button></div>${aForm()}<button class="btn primary" style="margin-top:14px" onclick="saveA()">حفظ الشقة</button>`)}

async function saveA(id){if(id&&!(await v58Confirm('تأكيد تعديل الشقة','سيتم حفظ التعديلات.')))return;try{const monthly=+($('rm')?.value||0),b={number:an.value,code:acode.value||an.value,area_id:+aa.value,status:ast.value,rent:monthly,size_m2:+az.value,rooms:+ro.value,baths:+ba.value,kitchen:1,floor:+fl.value,notes:no.value,rental_type:artype.value,daily_rent:+rd.value,monthly_rent:monthly,annual_rent:+ry.value,available_date:avdate.value||null,living_rooms:+lr.value,salons:+sal.value,balconies:+bal.value,availability_alert_days:+avdays.value||0,availability_alert_enabled:aven.checked};await api(id?'/api/apartments/'+id:'/api/apartments',{method:id?'PUT':'POST',body:JSON.stringify(b)});closeM();await load();notify('تم حفظ البيانات بنجاح')}catch(e){alert(e.message)}}
async function delA(id){if(!(await v58Confirm('تأكيد حذف الشقة','لا يمكن التراجع عن الحذف.')))return;try{await api('/api/apartments/'+id,{method:'DELETE'});closeM();await load();notify('تم حذف الشقة')}catch(e){alert(e.message)}}
async function deletePhoto(id){if(!(await v58Confirm('تأكيد حذف الصورة','سيتم حذف الصورة نهائياً.')))return;try{const d=D.documents.find(x=>x.id===id);await api('/api/documents/'+id,{method:'DELETE'});await load();if(d)editA(d.apartment_id);notify('تم حذف الصورة')}catch(e){alert(e.message)}}
async function deleteVideo(id,apartmentId){if(!(await v58Confirm('تأكيد حذف الفيديو','سيتم حذف الفيديو نهائياً.')))return;try{await api('/api/documents/'+id,{method:'DELETE'});await load();editA(apartmentId);notify('تم حذف الفيديو')}catch(e){alert(e.message)}}

async function shareApartmentPhotos(id){if(me?.role!=='owner')return alert('المشاركة متاحة للمالك فقط');const photos=D.documents.filter(d=>d.apartment_id===id&&d.kind==='صورة شقة');if(!photos.length)return alert('لا توجد صور لهذه الشقة');const box=document.createElement('div');box.className='wa-picker';box.innerHTML=`<div class="wa-picker-box"><div class="modalhead"><h3>🟢 WhatsApp — اختر الصور</h3><button class="btn ghost" id="pc">✕ إغلاق</button></div><div class="notice">حدد الصور التي تريد إرسالها كصور عادية.</div><div class="wa-photo-list">${photos.map((p,i)=>`<label class="wa-photo-item"><input type="checkbox" data-i="${i}"><img src="/uploads/${encodeURIComponent(p.filename)}" alt="صورة ${i+1}"></label>`).join('')}</div><div class="wa-range-actions"><button class="btn ghost" id="pa">تحديد الكل</button><button class="btn wa-btn" id="ps">🟢 WhatsApp — إرسال</button></div></div>`;document.body.appendChild(box);box.querySelector('#pc').onclick=()=>box.remove();box.querySelector('#pa').onclick=()=>box.querySelectorAll('input').forEach(cb=>{cb.checked=true;cb.closest('.wa-photo-item').classList.add('selected')});box.querySelector('#ps').onclick=async()=>{try{const chosen=[...box.querySelectorAll('input:checked')].map(cb=>photos[+cb.dataset.i]),files=[];for(const d of chosen){const r=await fetch('/uploads/'+encodeURIComponent(d.filename));if(r.ok){const b=await r.blob();files.push(new File([b],d.original_name||d.filename,{type:b.type||'image/jpeg'}))}}if(!files.length)return alert('حدد صورة واحدة على الأقل');await v511ShareFiles(files,'صور الشقة');box.remove()}catch(e){if(e.name!=='AbortError')alert(e.message)}}}
async function shareApartmentVideo(id){if(me?.role!=='owner')return alert('المشاركة متاحة للمالك فقط');const a=D.apartments.find(x=>x.id===id),d=D.documents.find(x=>x.apartment_id===id&&x.kind==='فيديو شقة');if(!a||!d)return alert('لا يوجد فيديو لهذه الشقة');try{const r=await fetch('/uploads/'+encodeURIComponent(d.filename));if(!r.ok)throw Error('تعذر تجهيز الفيديو');const b=await r.blob();await v511ShareFiles([new File([b],d.original_name||`فيديو-شقة-${a.number}.mp4`,{type:b.type||'video/mp4'})],`فيديو شقة ${a.number}`)}catch(e){if(e.name!=='AbortError')alert(e.message)}}
function videoHtml(d){return `<div class="video-wrap v55-video-card" onclick="openMiniVideo(${d.apartment_id})"><div class="v55-video-play-label">▶ تشغيل داخل التطبيق</div><video class="v55-video-thumb" muted playsinline preload="metadata" src="/uploads/${encodeURIComponent(d.filename)}"></video><div class="row" onclick="event.stopPropagation()"><span class="muted">🎥 ${esc(d.original_name)}</span><div class="v510-video-actions"><button class="btn ghost" onclick="openMiniVideo(${d.apartment_id})">▶ تشغيل</button>${me.role==='owner'?`<button class="btn wa-btn" onclick="shareApartmentVideo(${d.apartment_id})">🟢 WhatsApp — الفيديو</button><button class="btn ghost" onclick="downloadApartmentVideo(${d.id})">⬇ تحميل</button>`:''}${me.role!=='user'?`<button class="btn danger" onclick="deleteVideo(${d.id},${d.apartment_id})">حذف</button>`:''}</div></div></div>`}
async function downloadApartmentVideo(id){try{const d=D.documents.find(x=>x.id===id);if(!d)return;const r=await fetch('/uploads/'+encodeURIComponent(d.filename));if(!r.ok)throw Error('تعذر تحميل الفيديو');const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=d.original_name||`فيديو-${id}.mp4`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1200)}catch(e){alert(e.message)}}


async function saveT(){try{const renew=$('newRenew')?.dataset.on!=='0';const r=await api('/api/tenants',{method:'POST',body:JSON.stringify({name:tn.value,phone:tp.value,national_id:tid.value,apartment_id:ta.value?+ta.value:null,contract_start:cs.value,contract_end:ce.value,monthly_rent:+tr.value,deposit:+dep.value,status:'نشط',notes:tnote.value,renewal_enabled:renew})});const f=$('tidfile')?.files?.[0];if(f){const fd=new FormData();fd.append('file',f);fd.append('tenant_id',r.id);fd.append('kind','هوية/جواز');const rr=await fetch('/api/documents',{method:'POST',headers:{Authorization:'Bearer '+token},body:fd});const jj=await rr.json();if(!rr.ok)throw Error(jj.error||'تعذر رفع الهوية/الجواز')}closeM();await load();notify('تم حفظ المستأجر')}catch(e){alert(e.message)}}

function logs(){return `<div class="panel"><div class="head"><h3>سجل العمليات</h3>${me.role==='owner'?'<button class="btn danger" onclick="clearLogs()">🗑 مسح السجل</button>':''}</div><div class="timeline">${D.logs.map(l=>`<div class="event"><b>${esc(l.action)}</b> — ${esc(l.detail)}<br><small>${esc(l.created_at)} • ${esc(l.who)}</small></div>`).join('')||'<div class="empty">لا توجد عمليات</div>'}</div></div>`}
async function clearLogs(){if(me.role!=='owner')return;if(!(await v58Confirm('تأكيد مسح السجل','سيتم حذف سجل العمليات بالكامل.')))return;try{await api('/api/logs',{method:'DELETE'});await load();notify('تم مسح السجل')}catch(e){alert(e.message)}}

/* v5.13 final overrides: one authoritative implementation */
function home(){let s=D.stats||{};return `<div class="hero hero-v513"><div class="hero-copy"><div class="hero-brand"><div class="v513-logo3d">⌂</div><div><small>نظام احترافي لإدارة العقارات</small><h3>عقارات غرب عمّان</h3></div></div><p>إدارة الشقق والمستأجرين والعقود والدفعات والوثائق بطريقة فخمة ومنظمة.</p><button class="btn primary" onclick="nav('apartments')">إدارة العقارات</button></div></div><div class="stats"><div class="stat"><div class="n">${s.total||0}</div><div class="l">إجمالي الشقق</div></div><div class="stat"><div class="n">${s.available||0}</div><div class="l">متاحة</div></div><div class="stat"><div class="n">${s.soon||0}</div><div class="l">قريبة من التوفر</div></div><div class="stat"><div class="n">${s.rented||0}</div><div class="l">مؤجرة</div></div><div class="stat"><div class="n">${s.repair||0}</div><div class="l">صيانة</div></div><div class="stat"><div class="n">${Number(D.money?.total||0).toLocaleString()}</div><div class="l">دفعات هذا الشهر د.أ</div></div></div><div class="panel"><div class="head"><h3>أحدث الشقق</h3><button class="btn ghost" onclick="nav('apartments')">عرض الكل</button></div><div class="cards">${D.apartments.slice(0,6).map(card).join('')}</div></div><div class="panel"><div class="head"><h3>آخر العمليات</h3><button class="btn ghost" onclick="nav('logs')">السجل</button></div>${D.logs.slice(0,6).map(l=>`<div style="padding:10px 0;border-bottom:1px solid #eee7dc"><b>${esc(l.action)}</b> — ${esc(l.detail)} <small class="muted">${esc(l.created_at)}</small></div>`).join('')||'<div class="empty">لا توجد عمليات</div>'}</div>`}

function apartments(){return `<div class="panel"><div class="head"><h3>إدارة العقارات</h3>${me.role!=="user"?'<button class="btn primary" onclick="addA()">＋ إضافة شقة</button>':''}</div><div class="toolbar v59-search"><input id="aq" placeholder="بحث برقم الشقة أو المنطقة..." oninput="drawA()"><select id="arooms" onchange="drawA()"><option value="">كل الغرف</option><option value="1">1 غرفة</option><option value="2">2 غرف</option><option value="3">3 غرف</option><option value="4">4 غرف</option></select><select id="art" onchange="drawA()"><option value="">كل أنواع الإيجار</option><option>يومي</option><option>شهري</option><option>سنوي</option></select><select id="af" onchange="drawA()"><option value="">كل المناطق</option>${D.areas.map(a=>`<option>${esc(a.name)}</option>`).join('')}</select><select id="as" onchange="drawA()"><option value="">كل الحالات</option>${statuses.map(s=>`<option>${s}</option>`).join('')}</select><button class="btn primary" onclick="v511OpenPriceRange()">💰 بحث من سعر إلى سعر</button><button class="btn ghost" onclick="resetApartmentSearch()">مسح البحث</button></div><div id="alist" class="cards" style="margin-top:16px"></div></div>`}

function editA(id){const a=D.apartments.find(x=>x.id===id),photos=D.documents.filter(d=>d.apartment_id===id&&d.kind==='صورة شقة');modal(`<div class="modalhead"><h3>تفاصيل الشقة ${esc(a.number)}</h3><button class="btn ghost" onclick="closeM()">✕ إغلاق</button></div>${aForm(a)}${me.role==='owner'?`<div class="v55-share-row"><button class="btn wa-btn" onclick="shareApartmentDetails(${id})">🟢 WhatsApp — التفاصيل</button></div>`:''}<div class="panel" style="margin-top:14px;padding:14px"><div class="head"><h3>📷 صور الشقة</h3><span class="muted">${photos.length} صورة</span></div>${me.role==='owner'&&photos.length?`<button class="btn wa-btn" onclick="shareApartmentPhotos(${id})">🟢 WhatsApp — الصور</button>`:''}${me.role!=='user'?`<input id="apPhotos" type="file" accept="image/jpeg,image/png,image/webp" multiple onchange="uploadApartmentPhotos(${id})">`:''}<div id="photos_${id}" class="photos">${photos.length?photos.map((p,i)=>photoHtml(p,i)).join(''):'<div class="photoempty full">لا توجد صور لهذه الشقة</div>'}</div></div><div class="v513-export-note">🎥 تم إخفاء قسم الفيديو من تفاصيل الشقة حسب طلبك.</div><div style="display:flex;gap:8px;margin-top:14px;flex-wrap:wrap"><button class="btn primary" onclick="saveA(${id})">حفظ التعديل</button>${me.role==='owner'?`<button class="btn danger" onclick="delA(${id})">حذف الشقة</button>`:''}</div>`) }

function tenants(){return `<div class="panel"><div class="head"><h3>المستأجرون والعقود</h3>${me.role!=="user"?'<button class="btn primary" onclick="addT()">＋ إضافة مستأجر</button>':''}</div><table><thead><tr><th>المستأجر</th><th>الشقة</th><th>الهاتف</th><th>الإيجار</th><th>العقد</th><th>التجديد</th><th>الهوية/الجواز</th></tr></thead><tbody>${D.tenants.map(t=>{const doc=D.documents.find(d=>d.tenant_id===t.id&&d.kind==='هوية/جواز');const on=!!t.renewal_enabled;return `<tr><td><b>${esc(t.name)}</b></td><td>${esc(t.apartment||'—')}</td><td>${esc(t.phone)}</td><td>${Number(t.monthly_rent||0).toLocaleString()}</td><td>${esc(t.contract_start||'—')} → ${esc(t.contract_end||'—')}</td><td>${me.role!=='user'?`<button class="renew-toggle ${on?'renew-on':'renew-off'}" onclick="toggleRenewal(${t.id},${on?1:0})"><span class="renew-dot"></span><span class="renew-label">${on?'قابل للتجديد':'غير قابل للتجديد'}</span></button>`:`<span class="renew-toggle ${on?'renew-on':'renew-off'}"><span class="renew-dot"></span><span class="renew-label">${on?'قابل للتجديد':'غير قابل للتجديد'}</span></span>`}</td><td>${doc?`<button class="btn ghost" onclick="window.open('/uploads/${encodeURIComponent(doc.filename)}','_blank')">عرض</button>`:'—'}</td></tr>`}).join('')||'<tr><td colspan="7" class="empty">لا يوجد مستأجرون</td></tr>'}</tbody></table></div>`}

function addT(){modal(`<div class="modalhead"><h3>إضافة مستأجر وعقد</h3><button class="btn ghost" onclick="closeM()">✕ إغلاق</button></div><div class="formgrid"><div class="field"><label>الاسم</label><input id="tn"></div><div class="field"><label>الهاتف</label><input id="tp"></div><div class="field"><label>رقم الهوية</label><input id="tid"></div><div class="field"><label>الشقة</label><select id="ta"><option value="">بدون</option>${D.apartments.map(a=>`<option value="${a.id}">${a.number} — ${a.area}</option>`).join('')}</select></div><div class="field"><label>بداية العقد</label><input id="cs" type="date"></div><div class="field"><label>نهاية العقد</label><input id="ce" type="date"></div><div class="field"><label>الإيجار الشهري</label><input id="tr" type="number"></div><div class="field"><label>التأمين</label><input id="dep" type="number"></div><div class="field full"><label>صورة الهوية أو جواز السفر</label><input id="tidfile" type="file" accept="image/jpeg,image/png,image/webp"></div><div class="field full"><label>التجديد</label><button type="button" class="renew-toggle renew-on" id="newRenew" onclick="toggleNewRenewal(this)" data-on="1"><span class="renew-dot"></span><span class="renew-label">قابل للتجديد</span></button></div><div class="field full"><label>ملاحظات</label><textarea id="tnote"></textarea></div></div><button class="btn primary" style="margin-top:14px" onclick="saveT()">حفظ المستأجر</button>`) }
function toggleNewRenewal(btn){const on=btn.dataset.on!=='1';btn.dataset.on=on?'1':'0';btn.classList.toggle('renew-on',on);btn.classList.toggle('renew-off',!on);btn.innerHTML=`<span class="renew-dot"></span><span class="renew-label">${on?'قابل للتجديد':'غير قابل للتجديد'}</span>`}
async function toggleRenewal(id,current){try{const t=D.tenants.find(x=>x.id===id);if(!t)return;await api('/api/tenants/'+id,{method:'PUT',body:JSON.stringify({name:t.name,apartment_id:t.apartment_id,phone:t.phone,national_id:t.national_id,status:t.status,contract_start:t.contract_start,contract_end:t.contract_end,monthly_rent:t.monthly_rent,deposit:t.deposit,notes:t.notes,renewal_enabled:!current})});await load();notify(!current?'تم تحويل المستأجر إلى قابل للتجديد':'تم تحويل المستأجر إلى غير قابل للتجديد')}catch(e){alert(e.message)}}
async function downloadFullBackup(){if(me?.role!=='owner'){alert('حفظ النسخة الكاملة متاح للمالك فقط');return}if(!(await v58Confirm('حفظ نسخة كاملة','سيتم حفظ قاعدة البيانات والصور والمستندات والملفات الموجودة في الموقع في ملف نسخة احتياطية واحد.')))return;try{const r=await fetch('/api/export/full-backup',{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('تعذر إنشاء النسخة الاحتياطية');const b=await r.blob(),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='west-amman-backup-'+new Date().toISOString().slice(0,30)+'.tar.gz';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2000);notify('تم حفظ النسخة الاحتياطية كاملة')}catch(e){alert(e.message)}}
/* v5.14 WhatsApp details: direct WhatsApp text, no browser file-share dependency */
function buildWhatsAppDetails(a){
  const n=v=>String(v??'—');
  const money=v=>Number(v||0).toLocaleString('ar-JO');
  const lines=[
    '╔══════════════════════════════╗',
    '      🏠 عقارات غرب عمّان',
    '      تفاصيل الشقة الرسمية',
    '╚══════════════════════════════╝',
    '',
    `🔖 الكود: ${n(a.code||a.number)}`,
    `🏢 رقم الشقة: ${n(a.number)}`,
    `📍 المنطقة: ${n(a.area)}`,
    `🟢 الحالة: ${n(a.status)}`,
    '',
    '📐 المواصفات',
    `• الغرف: ${n(a.rooms)}`,
    `• الحمامات: ${n(a.baths)}`,
    `• الصالات: ${n(a.living_rooms)}`,
    `• الصالونات: ${n(a.salons)}`,
    `• البلكونات: ${n(a.balconies)}`,
    `• المساحة: ${n(a.size_m2)} م²`,
    `• الطابق: ${n(a.floor)}`,
    '',
    '💰 الأسعار',
    `• يومي: ${money(a.daily_rent)} د.أ`,
    `• شهري: ${money(a.monthly_rent||a.rent)} د.أ`,
    `• سنوي: ${money(a.annual_rent)} د.أ`,
    `• نوع الإيجار: ${n(a.rental_type)}`,
    '',
    '📅 التوفر',
    `• موعد التوفر: ${n(a.available_date||a.availability_date)}`,
    `• التنبيه قبل التوفر: ${n(a.availability_alert_days||0)} يوم`,
    '',
    '📝 الملاحظات',
    n(a.notes),
    '',
    '━━━━━━━━━━━━━━━━━━━━',
    'إدارة عقارات غرب عمّان'
  ];
  return lines.join('\n');
}
async function shareApartmentDetails(id){
  try{
    if(me?.role!=='owner'){alert('المشاركة متاحة للمالك فقط');return;}
    const a=D.apartments.find(x=>x.id===id);
    if(!a){alert('الشقة غير موجودة');return;}
    const text=buildWhatsAppDetails(a);
    const wa='https://wa.me/?text='+encodeURIComponent(text);
    window.location.href=wa;
  }catch(e){console.error(e);alert('تعذر فتح WhatsApp لإرسال التفاصيل.');}
}
