from pathlib import Path
p=Path('/mnt/data/project_new/index.html')
s=p.read_text(encoding='utf-8')
marker='\n<style id="v5481-authoritative-ui">'
if marker in s:
    s=s.split(marker)[0]
css=r'''
<style id="v5481-authoritative-ui">
:root{--n:#243744;--n2:#182832;--g:#ad9567;--g2:#d8c9a8;--bg:#f2f4f4;--c:#fff;--t:#263640;--m:#71808a;--line:#dce2e5;--soft:#eef2f3;--shadow:0 5px 16px rgba(28,43,52,.07)}
body{background:var(--bg)!important;color:var(--t)!important;font-family:Arial,"Noto Kufi Arabic",Tahoma,sans-serif!important}
.btn,.v55-share-btn,.wa-btn{transform:none!important;background-image:none!important;box-shadow:0 2px 7px rgba(25,40,50,.11)!important;border:1px solid rgba(36,55,68,.08)!important;border-radius:9px!important;font-weight:700!important}
.primary{background:#ad9567!important;color:#fff!important}.dark{background:#314754!important;color:#fff!important}.ghost{background:#eef2f3!important;color:#31434e!important}.success{background:#5d927b!important;color:#fff!important}.danger{background:#bd6468!important;color:#fff!important}
.side{background:linear-gradient(180deg,#243744,#182832)!important}.nav button{font-size:13px!important;padding:9px 10px!important}.top{background:#fff!important}.content{padding:18px!important}
.lux-property,.wa-property-card{border:1px solid #dce2e5!important;border-radius:18px!important;background:#fff!important;box-shadow:var(--shadow)!important;overflow:hidden}
/* Main and apartment cards: calm, compact, professional */
.v548-card-gallery{display:grid;grid-template-columns:2fr 1fr 1fr;grid-template-rows:92px 92px;gap:3px;background:#edf1f2;height:187px}.v548-card-gallery .v548-main{grid-row:1/3}.v548-card-gallery img{width:100%;height:100%;object-fit:cover;display:block}.v548-card-placeholder{display:grid;place-items:center;color:#8a959b;font-size:11px;background:#eef2f3}
.v548-card-body{padding:12px 13px 8px}.v548-card-title{font-size:16px!important;line-height:1.45!important;margin:0;color:#263744}.v548-card-area{font-size:11px;color:#77848b;margin-top:2px}.v548-card-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px 10px;margin-top:9px}.v548-card-grid div{font-size:10px;color:#7a868d;padding-bottom:4px;border-bottom:1px solid #edf0f1}.v548-card-grid b{color:#33464f;font-size:11px;font-weight:700}.v548-card-price{margin-top:8px;font-size:13px;font-weight:800;color:#665533}.v548-card-status{width:100%;padding:7px 10px 0}.v548-card-status .status-square{width:100%!important;justify-content:center!important;font-size:10px!important;padding:6px!important;border-radius:8px!important}.v548-card-actions{display:grid;grid-template-columns:1fr 1fr 1fr;gap:5px;padding:8px 10px 10px}.v548-card-actions button{min-height:31px!important;padding:5px 4px!important;font-size:9px!important;white-space:nowrap!important}.v548-detail{background:#314754!important;color:#fff!important}.v548-wa-details{background:#5e806f!important;color:#fff!important}.v548-wa-photos{background:#6f8790!important;color:#fff!important}
.v548-upload-wrap{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.v548-upload-btn{display:inline-flex;align-items:center;justify-content:center;min-height:38px;padding:8px 13px;border-radius:9px;background:#314754;color:#fff;border:0;box-shadow:0 2px 7px rgba(25,40,50,.12);font-size:12px;font-weight:700;cursor:pointer}.v548-upload-btn input{display:none}.v548-share-row-final{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:8px 0}.v548-share-row-final button{min-height:36px;font-size:11px!important}.v548-wa-picker{position:fixed;inset:0;z-index:30000;background:rgba(20,30,35,.58);display:flex;align-items:center;justify-content:center;padding:12px}.v548-wa-box{width:min(620px,95vw);max-height:88vh;overflow:auto;background:#fff;border-radius:18px;padding:15px;box-shadow:0 20px 60px rgba(0,0,0,.2)}.v548-photo-select-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.v548-photo-select{border:1px solid #dfe5e7;border-radius:10px;overflow:hidden;background:#f5f7f7}.v548-photo-select img{width:100%;height:130px;object-fit:cover;display:block}.v548-photo-select label{display:flex;gap:6px;align-items:center;padding:7px;font-size:11px}.v548-wa-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px}
@media(max-width:600px){
 .nav button{font-size:10px!important;padding:7px 8px!important}.content{padding:9px!important}.top{height:57px}.top h2{font-size:15px!important}.btn,.v55-share-btn,.wa-btn{font-size:9px!important;min-height:28px!important;padding:5px 6px!important}.v548-card-gallery{height:142px;grid-template-rows:69px 69px}.v548-card-body{padding:9px 10px 6px}.v548-card-title{font-size:14px!important}.v548-card-area{font-size:9px}.v548-card-grid{gap:4px 7px;margin-top:7px}.v548-card-grid div{font-size:8.5px}.v548-card-grid b{font-size:9.5px}.v548-card-price{font-size:11px;margin-top:6px}.v548-card-status{padding:5px 7px 0}.v548-card-status .status-square{font-size:9px!important;padding:5px!important}.v548-card-actions{gap:4px;padding:6px 7px 8px}.v548-card-actions button{font-size:8px!important;min-height:26px!important;padding:4px 3px!important}.v548-photo-select-grid{grid-template-columns:1fr 1fr}.v548-photo-select img{height:105px}.v548-share-row-final{grid-template-columns:1fr 1fr}.v548-upload-btn{font-size:11px;min-height:34px;padding:7px 10px}
}
</style>
'''
js=r'''
<script id="v5481-authoritative-js">
(function(){
  const canManage=()=>!!me&&['owner','admin'].includes(me.role);
  const canShare=()=>!!me&&['owner','admin'].includes(me.role);
  function escx(v){return typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
  function docsFor(id){return (D?.documents||[]).filter(d=>d.apartment_id===id&&d.kind==='صورة شقة').slice(0,4)}
  function gallery(a){const ph=docsFor(a.id);return `<div class="v548-card-gallery">${ph.map((p,i)=>`<div class="${i===0?'v548-main':''}"><img src="/uploads/${encodeURIComponent(p.filename)}?v=${encodeURIComponent(p.filename)}" alt="صورة الشقة" loading="lazy"></div>`).join('')}${Array.from({length:Math.max(0,4-ph.length)},(_,i)=>`<div class="v548-card-placeholder">صورة ${ph.length+i+1}</div>`).join('')}</div>`}
  function actions(a){return `<div class="v548-card-actions"><button class="btn v548-detail" type="button" data-act="detail" data-id="${a.id}">التفاصيل</button>${canShare()?`<button class="btn v548-wa-details" type="button" data-act="wa-details" data-id="${a.id}">واتساب التفاصيل</button><button class="btn v548-wa-photos" type="button" data-act="wa-photos" data-id="${a.id}">واتساب الصور</button>`:''}</div>`}
  function cardFinal(a){const ph=docsFor(a.id);const price=Number(a.monthly_rent||a.rent||0).toLocaleString();return `<article class="card wa-property-card" data-apartment-id="${a.id}">${gallery(a)}<div class="v548-card-body"><h4 class="v548-card-title">شقة ${escx(a.number)}</h4><div class="v548-card-area">${escx(a.area||'غير محدد')} · ${escx(a.rental_type||'شهري')}</div><div class="v548-card-grid"><div>الغرف <b>${a.rooms||0}</b></div><div>الحمامات <b>${a.baths||0}</b></div><div>الصالونات <b>${a.salons||a.living_rooms||0}</b></div><div>البلكونات <b>${a.balconies||0}</b></div><div>المساحة <b>${a.size_m2||0} م²</b></div><div>الطابق <b>${a.floor||0}</b></div></div>${me?.role==='owner'?`<div class="v548-card-price">${price} د.أ / ${escx(a.rental_type||'شهري')}</div>`:''}<div class="v548-card-status">${badge(a.status)}</div></div>${actions(a)}</article>`}
  function renderCards(){const root=document.getElementById('alist');if(!root)return;const q=(document.getElementById('aq')?.value||'').toLowerCase(),ar=document.getElementById('af')?.value||'',st=document.getElementById('as')?.value||'',rt=document.getElementById('art')?.value||'',rooms=Number(document.getElementById('arooms')?.value||0);let arr=(D?.apartments||[]).filter(a=>(`${a.number} ${a.area||''}`).toLowerCase().includes(q)&&(!ar||a.area===ar)&&(!st||a.status===st)&&(!rt||a.rental_type===rt)&&(!rooms||Number(a.rooms||0)===rooms));root.innerHTML=arr.length?arr.map(cardFinal).join(''):'<div class="empty">لا توجد نتائج</div>';}
  function apartmentViewFinal(){return `<div class="panel"><div class="head"><h3>الشقق</h3>${canManage()?'<button class="btn primary" onclick="addA()">إضافة شقة</button>':''}</div><div class="toolbar"><input id="aq" placeholder="بحث برقم الشقة أو المنطقة..." oninput="renderCards()"><select id="arooms" onchange="renderCards()"><option value="">كل الغرف</option><option value="1">1 غرفة</option><option value="2">2 غرف</option><option value="3">3 غرف</option><option value="4">4 غرف</option></select><select id="art" onchange="renderCards()"><option value="">كل أنواع الإيجار</option><option>يومي</option><option>شهري</option><option>سنوي</option></select><select id="af" onchange="renderCards()"><option value="">كل المناطق</option>${(D?.areas||[]).map(a=>`<option>${escx(a.name)}</option>`).join('')}</select><select id="as" onchange="renderCards()"><option value="">كل الحالات</option>${statuses.map(s=>`<option>${escx(s)}</option>`).join('')}</select></div><div id="alist" class="cards" style="margin-top:14px"></div></div>`}
  function homeFinal(){const latest=(D?.apartments||[]).slice(0,6);return `<section class="panel"><div class="head"><div><small>أحدث الإضافات</small><h3>أحدث الشقق</h3></div><button class="btn ghost" onclick="luxNav('apartments')">عرض جميع الشقق</button></div><div class="cards">${latest.length?latest.map(cardFinal).join(''):'<div class="empty">لا توجد شقق</div>'}</div></section>`}
  // Replace both visible card renderers with one authoritative version.
  window.apartments=apartmentViewFinal; window.home=function(){let base='';try{base=(typeof oldHomeBase==='function'?oldHomeBase():'')}catch{} return base+homeFinal()};
  // Event delegation makes the buttons work even when cards are re-rendered.
  document.addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(!b)return;const id=Number(b.dataset.id);if(b.dataset.act==='detail')editA(id);if(b.dataset.act==='wa-details')shareApartmentDetails(id);if(b.dataset.act==='wa-photos')shareApartmentPhotos(id);});
  window.renderCards=renderCards;
  window.uploadApartmentPhotos=async function(id){
    if(!canManage())return finalToast('رفع الصور متاح للمالك أو الأدمن فقط');
    const input=document.getElementById('v548PhotosInput');if(!input||!input.files.length)return finalToast('اختر الصور أولاً');
    const files=[...input.files];const bad=files.find(f=>!['image/jpeg','image/png','image/webp'].includes((f.type||'').toLowerCase()));if(bad)return finalToast('يسمح فقط JPG وPNG وWEBP');
    try{const fd=new FormData();files.forEach(f=>fd.append('photos',f,f.name));const r=await fetch('/api/apartments/'+id+'/photos',{method:'POST',headers:{Authorization:'Bearer '+token},body:fd,cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||('فشل رفع الصور: '+r.status));input.value='';await load();editA(id);finalToast('تم رفع الصور بنجاح');}catch(err){finalToast(err.message||'تعذر رفع الصور');}
  };
  window.shareApartmentDetails=function(id){if(!canShare())return finalToast('المشاركة متاحة للمالك أو الأدمن فقط');const a=D.apartments.find(x=>x.id===id);if(!a)return;const text=`عقارات عمان الغربية\nتفاصيل الشقة\nالشقة: ${a.number}\nالمنطقة: ${a.area||''}\nالغرف: ${a.rooms||0}\nالحمامات: ${a.baths||0}\nالصالونات: ${a.salons||a.living_rooms||0}\nالبلكونات: ${a.balconies||0}\nالمساحة: ${a.size_m2||0} م²\nالطابق: ${a.floor||0}\nالإيجار: ${Number(a.monthly_rent||a.rent||0).toLocaleString()} د.أ / ${a.rental_type||'شهري'}\nالحالة: ${a.status||''}\nرابط العرض: ${location.origin}/property/${id}`;window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank');};
  window.shareApartmentPhotos=function(id){if(!canShare())return finalToast('المشاركة متاحة للمالك أو الأدمن فقط');const photos=docsFor(id);if(!photos.length)return finalToast('لا توجد صور لهذه الشقة');const box=document.createElement('div');box.className='v548-wa-picker';box.innerHTML=`<div class="v548-wa-box"><div class="head"><h3>إرسال صور الشقة عبر واتساب</h3><button class="btn ghost" id="v548Close">إغلاق</button></div><div class="v548-photo-select-grid">${photos.map((p,i)=>`<div class="v548-photo-select"><img src="/uploads/${encodeURIComponent(p.filename)}" alt="صورة الشقة"><label><input type="checkbox" data-i="${i}"> اختيار الصورة ${i+1}</label></div>`).join('')}</div><div class="v548-wa-actions"><button class="btn ghost" id="v548All">تحديد الكل</button><button class="btn v548-wa-photos" id="v548Send">إرسال عبر واتساب</button></div></div>`;document.body.appendChild(box);box.querySelector('#v548Close').onclick=()=>box.remove();box.querySelector('#v548All').onclick=()=>box.querySelectorAll('input[type=checkbox]').forEach(x=>x.checked=true);box.querySelector('#v548Send').onclick=async()=>{const chosen=[...box.querySelectorAll('input[type=checkbox]:checked')].map(x=>photos[+x.dataset.i]);if(!chosen.length)return finalToast('اختر صورة واحدة على الأقل');const files=[];for(const d of chosen){const r=await fetch('/uploads/'+encodeURIComponent(d.filename),{credentials:'same-origin',cache:'no-store'});if(r.ok){const b=await r.blob();files.push(new File([b],d.original_name||d.filename,{type:b.type||'image/jpeg'}))}}if(navigator.share&&navigator.canShare&&navigator.canShare({files})){try{await navigator.share({title:'صور الشقة',text:'صور الشقة',files})}catch(e){}box.remove();}else{const a=D.apartments.find(x=>x.id===id);window.open('https://wa.me/?text='+encodeURIComponent(`صور الشقة ${a?.number||''}\n`+chosen.map(d=>location.origin+'/uploads/'+encodeURIComponent(d.filename)).join('\n')),'_blank');box.remove();}};};
  // Authoritative edit dialog with a real upload button (not onchange-only).
  window.editA=function(id){const a=D.apartments.find(x=>x.id===id);if(!a)return;const photos=(D.documents||[]).filter(d=>d.apartment_id===id&&d.kind==='صورة شقة');modal(`<div class="modalhead"><h3>تفاصيل الشقة ${escx(a.number)}</h3><button class="btn ghost" onclick="closeM()">إغلاق</button></div>${aForm(a)}${canShare()?`<div class="v548-share-row-final"><button class="btn v548-wa-details" onclick="shareApartmentDetails(${id})">واتساب التفاصيل</button><button class="btn v548-wa-photos" onclick="shareApartmentPhotos(${id})">واتساب الصور</button></div>`:''}<div class="panel" style="margin-top:12px"><div class="head"><h3>صور الشقة</h3><span class="muted">${photos.length} صورة</span></div>${canManage()?`<div class="v548-upload-wrap"><label class="v548-upload-btn">رفع صور الشقة<input id="v548PhotosInput" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><button class="btn primary" type="button" id="v548UploadNow">حفظ الصور</button><span class="muted">JPG / PNG / WEBP</span></div>`:''}<div class="photos" style="margin-top:10px">${photos.length?photos.map((p,i)=>photoHtml(p,i)).join(''):'<div class="photoempty full">لا توجد صور لهذه الشقة</div>'}</div></div><div style="display:flex;gap:7px;margin-top:12px;flex-wrap:wrap"><button class="btn primary" onclick="saveA(${id})">حفظ التعديل</button>${me?.role==='owner'?`<button class="btn danger" onclick="delA(${id})">حذف الشقة</button>`:''}</div>`);const up=document.getElementById('v548UploadNow');if(up)up.onclick=()=>uploadApartmentPhotos(id);};
  const oldHomeBase=window.home; // captured after declarations above; retained only if another wrapper calls it later
  setTimeout(()=>{try{renderCards()}catch{}},0);
})();
</script>
'''
# insert before final closing html if exists
idx=s.rfind('</html>')
if idx==-1: s+=css+js
else: s=s[:idx]+css+js+s[idx:]
p.write_text(s,encoding='utf-8')
