from pathlib import Path
p=Path('/mnt/data/project_new/index.html'); s=p.read_text()
# remove URL from the authoritative share details function
s=s.replace("\\nرابط العرض: ${location.origin}/property/${id}`;window.open", "`;window.open")
# add tasks nav to authoritative shell by inserting after finance nav
needle="        ${navBtn('finance','د.أ','الدفعات والمالية')}"
if needle in s and "navBtn('tasks'" not in s:
    s=s.replace(needle, needle+"\n        ${[\"owner\",\"admin\"].includes(me.role)?navBtn('tasks','✓','مهام Admin'):''}",1)
# Add tasks title
s=s.replace('const titles={home:"الرئيسية",apartments:"الشقق والعقارات",tenants:"المستأجرون والعقود",finance:"الدفعات والمالية",users:', 'const titles={home:"الرئيسية",apartments:"الشقق والعقارات",tenants:"المستأجرون والعقود",finance:"الدفعات والمالية",tasks:"مهام Admin",users:',1)
# inject authoritative UI before closing html
addon=r'''
<style id="v549-final-ui">
:root{--n:#334955!important;--n2:#253943!important;--g:#7b8790!important;--g2:#d9e0e4!important;--bg:#f3f5f6!important;--c:#ffffff!important;--t:#26343b!important;--m:#6d7880!important;--line:#dfe5e8!important;--shadow:0 8px 22px rgba(32,45,52,.08)!important}
.primary{background:#5f717b!important;color:#fff!important;box-shadow:0 2px 6px rgba(31,45,52,.12)!important}.dark{background:#435760!important;color:#fff!important}.ghost{background:#eef2f4!important;color:#334955!important;box-shadow:0 2px 6px rgba(31,45,52,.08)!important}.danger{background:#b45b5b!important;box-shadow:0 2px 6px rgba(31,45,52,.08)!important}.success{background:#547c6c!important;box-shadow:0 2px 6px rgba(31,45,52,.08)!important}
.btn,.v55-share-btn{box-shadow:0 2px 6px rgba(31,45,52,.10)!important;transform:none!important}
.status-square{font-weight:900!important;filter:saturate(.85) brightness(.92)}.status-square.available{background:#c5e4d4!important;color:#185b42!important}.status-square.near{background:#e8d99c!important;color:#5f5113!important}.status-square.soon{background:#c9dceb!important;color:#315a73!important}.status-square.reserved{background:#e6c6b4!important;color:#75422b!important}.status-square.repair{background:#e5c0c0!important;color:#7d3030!important}
.lux-gold-line{background:#7b8790!important}.lux-stat b{color:#334955!important}.lux-side{background:linear-gradient(180deg,#334955,#253943)!important}.lux-hero{background:#334955!important}.lux-property{border-color:#dfe5e8!important;box-shadow:0 7px 18px rgba(32,45,52,.07)!important}.lux-property .lux-prop-price{color:#435760!important}.lux-prop-actions .btn{box-shadow:0 2px 5px rgba(31,45,52,.08)!important}
.v549-task-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.v549-task{border:1px solid var(--line);border-radius:14px;padding:12px;background:#fff}.v549-task.done{opacity:.72}.v549-task-title{font-weight:800;color:#334955}.v549-task-meta{font-size:11px;color:var(--m);line-height:1.7;margin-top:5px}.v549-task-actions{display:flex;gap:6px;margin-top:9px}.v549-task-actions button{font-size:10px!important;padding:5px 7px!important;min-height:28px!important}.v549-user-card{border:1px solid var(--line)!important;background:#fff!important}.v549-pass-row{display:flex;gap:6px;align-items:center}.v549-pass-row input{flex:1}.v549-pass-toggle{min-width:58px!important;font-size:10px!important}
.v549-home-tasks{margin-top:14px}.v549-home-tasks .v549-task-grid{grid-template-columns:repeat(2,minmax(0,1fr))}
@media(max-width:800px){.v549-task-grid,.v549-home-tasks .v549-task-grid{grid-template-columns:1fr}.lux-nav button{font-size:11px!important;padding:8px 9px!important}.lux-nav button span{font-size:12px!important}.btn,.v55-share-btn{font-size:10px!important;min-height:30px!important;padding:5px 7px!important}.lux-property b{font-size:14px!important}.lux-property small{font-size:10.5px!important}.lux-property .lux-prop-meta{font-size:10px!important}}
</style>
<script>
(function(){
  const oldView=window.view;
  window.shareApartmentDetails=function(id){
    if(!(me&&['owner','admin'].includes(me.role)))return finalToast('المشاركة متاحة للمالك أو الأدمن فقط');
    const a=D.apartments.find(x=>x.id===id); if(!a)return;
    const text=`عقارات عمان الغربية\nتفاصيل الشقة\nالشقة: ${a.number}\nالمنطقة: ${a.area||''}\nالغرف: ${a.rooms||0}\nالحمامات: ${a.baths||0}\nالصالونات: ${a.salons||a.living_rooms||0}\nالبلكونات: ${a.balconies||0}\nالمساحة: ${a.size_m2||0} م²\nالطابق: ${a.floor||0}\nالإيجار: ${Number(a.monthly_rent||a.rent||0).toLocaleString()} د.أ / ${a.rental_type||'شهري'}\nالحالة: ${a.status||''}`;
    window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank');
  };
  window.shareApartmentPhotos=function(id){
    if(!(me&&['owner','admin'].includes(me.role)))return finalToast('المشاركة متاحة للمالك أو الأدمن فقط');
    const photos=docsFor(id); if(!photos.length)return finalToast('لا توجد صور لهذه الشقة');
    const box=document.createElement('div'); box.className='v548-wa-picker';
    box.innerHTML=`<div class="v548-wa-box"><div class="head"><h3>إرسال صور الشقة عبر WhatsApp</h3><button class="btn ghost" id="v549Close">إغلاق</button></div><div class="v548-photo-select-grid">${photos.map((p,i)=>`<div class="v548-photo-select"><img src="/uploads/${encodeURIComponent(p.filename)}" alt="صورة الشقة"><label><input type="checkbox" data-i="${i}"> اختيار الصورة ${i+1}</label></div>`).join('')}</div><div class="v548-wa-actions"><button class="btn ghost" id="v549All">تحديد الكل</button><button class="btn primary" id="v549Send">إرسال الصور</button></div></div>`;
    document.body.appendChild(box); box.querySelector('#v549Close').onclick=()=>box.remove(); box.querySelector('#v549All').onclick=()=>box.querySelectorAll('input[type=checkbox]').forEach(x=>x.checked=true);
    box.querySelector('#v549Send').onclick=async()=>{const chosen=[...box.querySelectorAll('input[type=checkbox]:checked')].map(x=>photos[+x.dataset.i]);if(!chosen.length)return finalToast('اختر صورة واحدة على الأقل');const files=[];for(const d of chosen){const r=await fetch('/uploads/'+encodeURIComponent(d.filename),{credentials:'same-origin',cache:'no-store'});if(r.ok){const b=await r.blob();files.push(new File([b],d.original_name||d.filename,{type:b.type||'image/jpeg'}))}}if(navigator.share&&files.length&&navigator.canShare&&navigator.canShare({files})){try{await navigator.share({title:'صور الشقة',files})}catch(e){}box.remove();}else{window.open('https://wa.me/?text='+encodeURIComponent('صور الشقة '+(D.apartments.find(x=>x.id===id)?.number||'')),'_blank');box.remove();}};
  };
  window.uploadApartmentPhotos=async function(id){
    if(!(me&&['owner','admin'].includes(me.role)))return finalToast('رفع الصور متاح للمالك أو الأدمن فقط');
    const input=document.getElementById('v549PhotosInput'); if(!input||!input.files.length)return finalToast('اختر الصور أولاً');
    try{const fd=new FormData();[...input.files].forEach(f=>fd.append('photos',f,f.name));const r=await fetch('/api/apartments/'+id+'/photos',{method:'POST',headers:{Authorization:'Bearer '+token},body:fd,cache:'no-store'});const j=await r.json().catch(()=>({error:'تعذر قراءة رد الخادم'}));if(!r.ok)throw Error(j.error||'فشل رفع الصور');input.value='';await load();editA(id);finalToast('تم رفع الصور بنجاح')}catch(e){finalToast(e.message||'تعذر رفع الصور')}
  };
  window.adminPassword=function(id,username){modal(`<div class="modalhead"><h3>تغيير كلمة مرور Admin</h3><button class="btn ghost" onclick="closeM()">إغلاق</button></div><div class="notice">Admin: <b>${esc(username)}</b></div><div class="field"><label>كلمة المرور الجديدة</label><div class="v549-pass-row"><input id="apNewPass" type="password" minlength="6"><button class="btn ghost v549-pass-toggle" type="button" onclick="toggle549Pass('apNewPass',this)">إظهار</button></div></div><div class="field"><label>تأكيد كلمة المرور</label><div class="v549-pass-row"><input id="apNewPass2" type="password" minlength="6"><button class="btn ghost v549-pass-toggle" type="button" onclick="toggle549Pass('apNewPass2',this)">إظهار</button></div></div><button class="btn primary" onclick="saveAdminPassword(${id})">حفظ كلمة المرور</button>`)};
  window.toggle549Pass=function(id,b){const x=document.getElementById(id);x.type=x.type==='password'?'text':'password';b.textContent=x.type==='password'?'إظهار':'إخفاء'};
  window.saveAdminPassword=async function(id){const a=document.getElementById('apNewPass'),b=document.getElementById('apNewPass2');if(!a||a.value.length<6)return finalToast('كلمة المرور 6 أحرف/أرقام على الأقل');if(a.value!==b.value)return finalToast('كلمتا المرور غير متطابقتين');try{await api('/api/admins/'+id+'/password',{method:'PUT',body:JSON.stringify({newPassword:a.value})});closeM();finalToast('تم تغيير كلمة مرور Admin بنجاح')}catch(e){finalToast(e.message)}};
  window.tasksPage=function(){const tasks=D.tasks||[];const admins=(D._admins||[]);return `<div class="panel"><div class="head"><div><h3>مهام وواجبات Admin</h3><span class="muted">المهام تظهر أيضًا في الصفحة الرئيسية</span></div>${me.role==='owner'?'<button class="btn primary" onclick="addTask549()">إضافة مهمة</button>':''}</div><div class="v549-task-grid">${tasks.length?tasks.map(t=>`<div class="v549-task ${t.status==='مكتملة'?'done':''}"><div class="v549-task-title">${esc(t.title)}</div><div class="v549-task-meta">${esc(t.description||'بدون وصف')}<br>المسند إلى: ${esc(t.assigned_username||'غير محدد')}<br>الاستحقاق: ${esc(t.due_date||'بدون تاريخ')}<br>الحالة: ${esc(t.status)}</div><div class="v549-task-actions">${t.status!=='مكتملة'&&((me.role==='owner')||t.assigned_to===me.id)?`<button class="btn success" onclick="setTask549(${t.id},'مكتملة')">إتمام</button>`:''}${me.role==='owner'?`<button class="btn danger" onclick="deleteTask549(${t.id})">حذف</button>`:''}</div></div>`).join(''):'<div class="empty">لا توجد مهام</div>'}</div></div>`};
  window.addTask549=async function(){try{const r=await api('/api/users');const admins=(r.users||r||[]).filter(u=>u.role==='admin'&&u.active);modal(`<div class="modalhead"><h3>إضافة مهمة لـ Admin</h3><button class="btn ghost" onclick="closeM()">إغلاق</button></div><div class="field"><label>عنوان المهمة</label><input id="tTitle"></div><div class="field"><label>التفاصيل</label><textarea id="tDesc"></textarea></div><div class="field"><label>Admin المسؤول</label><select id="tAdmin">${admins.map(a=>`<option value="${a.id}">${esc(a.username)}</option>`).join('')}</select></div><div class="field"><label>تاريخ الاستحقاق</label><input id="tDue" type="date"></div><button class="btn primary" onclick="saveTask549()">حفظ المهمة</button>`)}catch(e){finalToast(e.message)}};
  window.saveTask549=async function(){try{await api('/api/tasks',{method:'POST',body:JSON.stringify({title:tTitle.value,description:tDesc.value,assigned_to:+tAdmin.value,due_date:tDue.value})});closeM();await load();finalToast('تمت إضافة المهمة')}catch(e){finalToast(e.message)}};
  window.setTask549=async function(id,status){try{await api('/api/tasks/'+id,{method:'PUT',body:JSON.stringify({status})});await load();finalToast('تم تحديث المهمة')}catch(e){finalToast(e.message)}};
  window.deleteTask549=async function(id){try{await api('/api/tasks/'+id,{method:'DELETE'});await load();finalToast('تم حذف المهمة')}catch(e){finalToast(e.message)}};
  window.users=function(){return `<div class="panel"><div class="head"><div><h3>المستخدمون والصلاحيات</h3><span class="muted">المالك يدير جميع حسابات Admin وكلمات مرورهم</span></div>${me.role==='owner'?'<button class="btn primary" onclick="addU()">إضافة Admin</button>':''}</div><div id="usersProfiles" class="v533-user-grid"><div class="empty">جاري تحميل المستخدمين…</div></div></div>`};
  window.loadUsersProfiles=async function(){const box=document.getElementById('usersProfiles');if(!box)return;try{const j=await api('/api/users');const list=(j.users||j||[]).filter(u=>u.role==='owner'||u.role==='admin');box.innerHTML=list.map(u=>`<div class="v533-user-card v549-user-card"><div class="v533-user-top"><div><div class="v533-user-name">${esc(u.username)}</div><div class="v533-user-role">${u.role==='owner'?'المالك':'Admin'} • ${u.active?'مفعّل':'متوقف'}</div></div>${u.role==='admin'&&me.role==='owner'?`<div style="display:flex;gap:6px;flex-wrap:wrap"><button class="btn primary" onclick="openUserPermissions(${u.id})">الصلاحيات</button><button class="btn dark" onclick="adminPassword(${u.id},'${esc(u.username)}')">تغيير كلمة السر</button></div>`:''}</div><div class="v533-perm-summary">${u.role==='owner'?'إدارة كاملة':'Admin: إدارة المهام والصلاحيات المسموحة'}</div></div>`).join('')||'<div class="empty">لا يوجد Admin</div>'}catch(e){box.innerHTML='<div class="notice">'+esc(e.message)+'</div>'}};
  window.view=function(){if(page==='tasks')return tasksPage();return page==='home'?home():page==='apartments'?apartments():page==='tenants'?tenants():page==='finance'?finance():page==='users'?users():page==='chat'?chat():page==='security'?securityBackupPage():logs()};
  const oldHome=window.home;
  window.home=function(){const base=oldHome();const tasks=D.tasks||[];const pending=tasks.filter(t=>t.status==='معلقة').slice(0,4);return base+((me&&['owner','admin'].includes(me.role))?`<section class="panel v549-home-tasks"><div class="head"><div><small>متابعة يومية</small><h3>مهام Admin</h3></div><button class="btn ghost" onclick="luxNav('tasks')">عرض كل المهام</button></div><div class="v549-task-grid">${pending.length?pending.map(t=>`<div class="v549-task"><div class="v549-task-title">${esc(t.title)}</div><div class="v549-task-meta">${esc(t.assigned_username||'غير محدد')} • ${esc(t.due_date||'بدون موعد')}</div></div>`).join(''):'<div class="empty">لا توجد مهام معلقة</div>'}</div></section>`:'')};
  window.render=function(){shell();if(page==='apartments')drawA();if(page==='chat')loadChat();if(page==='users')setTimeout(loadUsersProfiles,60)};
  setTimeout(()=>{try{render()}catch(e){}},20);
})();
</script>
'''
if '</html>' in s:
    s=s.replace('</html>',addon+'</html>',1)
else: s += addon
p.write_text(s)
