const express=require("express");
const path=require("path");
const app=express();
const PORT=process.env.PORT||10000,ROOT=__dirname;
const SUPABASE_URL=(process.env.SUPABASE_URL||"").replace(/\/+$/,"");
const SERVICE=process.env.SUPABASE_SERVICE_ROLE_KEY||"";
const OWNER_EMAIL=(process.env.OWNER_EMAIL||"").trim().toLowerCase();
const BUCKET=process.env.SUPABASE_BUCKET||"property-images";
app.disable("x-powered-by");app.use(express.json({limit:"25mb"}));app.use(express.urlencoded({extended:true,limit:"25mb"}));
const cfg=()=>!!(SUPABASE_URL&&SERVICE);
async function sb(pathname,opt={}){if(!cfg())throw Error("Supabase environment variables are missing.");const r=await fetch(SUPABASE_URL+pathname,{...opt,headers:{apikey:SERVICE,Authorization:"Bearer "+SERVICE,"Content-Type":"application/json",...(opt.headers||{})}});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok){const e=new Error(d?.msg||d?.message||d?.error_description||d?.error||t||("HTTP "+r.status));e.status=r.status;e.data=d;throw e}return d}
async function current(req){const h=String(req.headers.authorization||"");if(!h.startsWith("Bearer "))return null;try{const u=await sb("/auth/v1/user",{headers:{Authorization:h}});if(!u?.id)return null;const p=(await sb("/rest/v1/profiles?id=eq."+encodeURIComponent(u.id)+"&select=id,name,email,role,permissions"))?.[0];return p&&["owner","admin"].includes(p.role)?{...p,token:h.slice(7),authUser:u}:null}catch{return null}}
async function staff(req,res,next){const u=await current(req);if(!u)return res.status(401).json({ok:false,error:"غير مصرح. سجل الدخول من جديد."});req.staff=u;next()}
async function owner(req,res,next){const u=await current(req);if(!u||u.role!=="owner")return res.status(403).json({ok:false,error:"هذه العملية متاحة للمالك فقط."});req.staff=u;next()}
app.post("/api/login",async(req,res)=>{try{const email=String(req.body?.email||"").trim().toLowerCase(),password=String(req.body?.password||"");if(!email||!password)return res.status(400).json({ok:false,message:"أدخل البريد الإلكتروني وكلمة المرور."});const a=await sb("/auth/v1/token?grant_type=password",{method:"POST",body:JSON.stringify({email,password})});const id=a?.user?.id;if(!id)return res.status(401).json({ok:false,message:"بيانات الدخول غير صحيحة."});let p=(await sb("/rest/v1/profiles?id=eq."+encodeURIComponent(id)+"&select=id,name,email,role,permissions"))?.[0];if(!p){const any=await sb("/rest/v1/profiles?select=id&limit=1");if(any?.length&&!OWNER_EMAIL)return res.status(403).json({ok:false,message:"هذا الحساب غير مصرح به."});p=(await sb("/rest/v1/profiles",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({id,name:a.user?.user_metadata?.name||"المالك",email,role:"owner",permissions:["dashboard","properties","tenants","reports","settings","admins","messages"]})}))?.[0]}res.json({ok:true,token:a.access_token,user:{id:p.id,name:p.name||email,email:p.email||email,role:p.role,permissions:p.permissions||[]}})}catch(e){res.status(e.status===400||e.status===401?e.status:500).json({ok:false,message:e.message||"تعذر تسجيل الدخول."})}});
app.get("/api/public/properties",async(req,res)=>{try{res.json(await sb("/rest/v1/properties?select=*&order=created_at.desc")||[])}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.get("/api/properties",staff,async(req,res)=>{try{res.json(await sb("/rest/v1/properties?select=*&order=created_at.desc")||[])}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post("/api/upload",staff,async(req,res)=>{try{
  const request=new Request("http://localhost"+req.originalUrl,{method:"POST",headers:req.headers,body:req,duplex:"half"});
  const form=await request.formData();
  const files=form.getAll("images").filter(x=>x&&typeof x.arrayBuffer==="function").slice(0,10);
  const urls=[];
  for(const file of files){
    const type=String(file.type||"");
    if(!["image/jpeg","image/png","image/webp"].includes(type)) continue;
    const ext=type==="image/png"?"png":type==="image/webp"?"webp":"jpg";
    const base=String(file.name||"image").replace(/[^a-zA-Z0-9._-]/g,"_").replace(/\.[^.]+$/," ").trim().slice(0,50)||"image";
    const objectPath=`properties/${Date.now()}-${Math.random().toString(36).slice(2,10)}-${base}.${ext}`;
    const r=await fetch(`${SUPABASE_URL}/storage/v1/object/${BUCKET}/${objectPath}`,{method:"POST",headers:{apikey:SERVICE,Authorization:"Bearer "+SERVICE,"Content-Type":type,"x-upsert":"false","Cache-Control":"3600"},body:Buffer.from(await file.arrayBuffer())});
    const t=await r.text();if(!r.ok)throw Error(t||`فشل رفع الصورة (${r.status})`);
    urls.push(`${SUPABASE_URL}/storage/v1/object/public/${BUCKET}/${objectPath}`);
  }
  res.json({ok:true,urls});
}catch(e){res.status(500).json({ok:false,error:e.message||"تعذر رفع الصور."})}});
function propertyRow(b){return {code:String(b.code||"").trim(),name:String(b.name||"").trim(),area:String(b.area||"").trim(),status:String(b.status||"متاحة"),floor:b.floor===""||b.floor==null?null:Number(b.floor),area_size:b.areaSize===""||b.areaSize==null?null:Number(b.areaSize),price:Number(b.price||0),rooms:Number(b.rooms||0),baths:Number(b.baths||0),balcony:Boolean(Number(b.balcony||0)),availability_date:b.availabilityDate||null,alert_days:Math.max(0,Number(b.alertDays??7)),notes:String(b.notes||""),video_url:String(b.video||""),images:Array.isArray(b.images)?b.images.filter(Boolean).slice(0,10):[]}}
app.post("/api/properties",staff,async(req,res)=>{try{const row=propertyRow(req.body||{});if(!row.code||!row.name||!row.area)return res.status(400).json({ok:false,error:"الكود واسم الشقة والمنطقة مطلوبة."});const r=await sb("/rest/v1/properties",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(row)});res.json(r?.[0]||r)}catch(e){res.status(e.status||500).json({ok:false,error:e.message||"تعذر حفظ الشقة."})}});
app.put("/api/properties/:id",staff,async(req,res)=>{try{const row=propertyRow(req.body||{});const r=await sb("/rest/v1/properties?id=eq."+encodeURIComponent(req.params.id),{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(row)});res.json(r?.[0]||r)}catch(e){res.status(e.status||500).json({ok:false,error:e.message||"تعذر تعديل الشقة."})}});
app.delete("/api/properties/:id",staff,async(req,res)=>{try{await sb("/rest/v1/properties?id=eq."+encodeURIComponent(req.params.id),{method:"DELETE"});res.json({ok:true})}catch(e){res.status(e.status||500).json({ok:false,error:e.message||"تعذر حذف الشقة."})}});
app.get("/api/users",staff,async(req,res)=>{try{res.json(await sb("/rest/v1/profiles?select=id,name,email,role,permissions&order=created_at.asc")||[])}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post("/api/users",owner,async(req,res)=>{try{const name=String(req.body?.name||"").trim(),email=String(req.body?.email||"").trim().toLowerCase(),password=String(req.body?.password||"");if(!name||!email||password.length<6)return res.status(400).json({ok:false,error:"أكمل الاسم والبريد وكلمة المرور (6 أحرف على الأقل)."});const c=await sb("/auth/v1/admin/users",{method:"POST",body:JSON.stringify({email,password,email_confirm:true,user_metadata:{name}})}),id=c?.id||c?.user?.id;if(!id)throw Error("لم يتم إنشاء حساب المدير.");const permissions=Array.isArray(req.body?.permissions)?req.body.permissions:["dashboard","properties"];const r=await sb("/rest/v1/profiles",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({id,name,email,role:"admin",permissions})});res.json(r?.[0]||r)}catch(e){res.status(e.status||500).json({ok:false,error:e.message||"تعذر إنشاء المدير."})}});
app.put("/api/users/:id",owner,async(req,res)=>{try{const id=String(req.params.id),name=String(req.body?.name||"").trim(),email=String(req.body?.email||"").trim().toLowerCase(),password=String(req.body?.password||"");if(!name||!email)return res.status(400).json({ok:false,error:"أكمل الاسم والبريد الإلكتروني."});const authBody={email,user_metadata:{name}};if(password)authBody.password=password;await sb("/auth/v1/admin/users/"+encodeURIComponent(id),{method:"PUT",body:JSON.stringify(authBody)});const permissions=Array.isArray(req.body?.permissions)?req.body.permissions:[];const r=await sb("/rest/v1/profiles?id=eq."+encodeURIComponent(id),{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({name,email,permissions})});res.json(r?.[0]||{id,name,email,permissions})}catch(e){res.status(e.status||500).json({ok:false,error:e.message||"تعذر تعديل المستخدم."})}});
app.put("/api/users/:id/password",owner,async(req,res)=>{try{if(String(req.params.id)!==String(req.staff.id))return res.status(403).json({ok:false,error:"يمكن للمالك تغيير كلمة مرور حسابه فقط."});const password=String(req.body?.password||"");if(password.length<6)return res.status(400).json({ok:false,error:"كلمة المرور يجب أن تكون 6 أحرف على الأقل."});await sb("/auth/v1/admin/users/"+encodeURIComponent(req.staff.id),{method:"PUT",body:JSON.stringify({password})});res.json({ok:true})}catch(e){res.status(e.status||500).json({ok:false,error:e.message||"تعذر تغيير كلمة المرور."})}});
app.get("/api/app-state",staff,async(req,res)=>{try{const r=await sb("/rest/v1/app_state?user_id=eq."+encodeURIComponent(req.staff.id)+"&select=data");res.json(r?.[0]?.data||{})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.put("/api/app-state",staff,async(req,res)=>{try{const row={user_id:req.staff.id,data:req.body||{},updated_at:new Date().toISOString()};const r=await sb("/rest/v1/app_state",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(row)});res.json(r?.[0]||row)}catch(e){res.status(e.status||500).json({ok:false,error:e.message})}});
app.get("/health",(req,res)=>res.json({ok:true,service:"west-amman-property-manager",version:"18.2.0",supabaseConfigured:cfg()}));
app.use(express.static(ROOT,{index:"index.html"}));app.get("*splat",(req,res)=>res.sendFile(path.join(ROOT,"index.html")));app.listen(PORT,"0.0.0.0",()=>console.log("West Amman Property Manager running on "+PORT));
