import express from 'express';
import session from 'express-session';
import bcrypt from 'bcryptjs';
import Database from 'better-sqlite3';
import multer from 'multer';
import path from 'path';
import {fileURLToPath} from 'url';
import {v4 as uuid} from 'uuid';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express();
const db=new Database(path.join(__dirname,'data.db'));
db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT UNIQUE,password TEXT,role TEXT,permissions TEXT);CREATE TABLE IF NOT EXISTS apartments(id TEXT PRIMARY KEY,code TEXT UNIQUE,area TEXT,neighborhood TEXT,address TEXT,rooms INTEGER,bathrooms INTEGER,living INTEGER, salon INTEGER, balcony INTEGER,space REAL,floor TEXT,rent REAL,deposit REAL,status TEXT,details TEXT,available_date TEXT,alert_days INTEGER,created_at TEXT);CREATE TABLE IF NOT EXISTS images(id TEXT PRIMARY KEY,apartment_id TEXT,file TEXT,original TEXT,created_at TEXT);CREATE TABLE IF NOT EXISTS tenants(id TEXT PRIMARY KEY,apartment_id TEXT,name TEXT,phone TEXT,rent REAL,start_date TEXT,end_date TEXT,deposit REAL,renewal TEXT,document TEXT,notes TEXT);CREATE TABLE IF NOT EXISTS finance(id TEXT PRIMARY KEY,type TEXT,category TEXT,amount REAL,date TEXT,apartment_id TEXT,notes TEXT);CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY,title TEXT,details TEXT,due_date TEXT,priority TEXT,assigned_to TEXT,status TEXT);`);
const count=db.prepare('SELECT COUNT(*) c FROM users').get().c;if(!count){db.prepare('INSERT INTO users VALUES (?,?,?,?,?)').run(uuid(),'owner',bcrypt.hashSync('Owner@1234',10),'owner',JSON.stringify(['*']));}
app.use(express.json());app.use(express.urlencoded({extended:true}));app.use(session({secret:process.env.SESSION_SECRET||'change-this-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:false,maxAge:1000*60*60*12}}));
const upload=multer({dest:path.join(__dirname,'uploads'),limits:{files:40,fileSize:15*1024*1024},fileFilter:(r,f,cb)=>cb(null,/^image\/(jpeg|png|webp)$/.test(f.mimetype))});
const auth=(req,res,next)=>{if(!req.session.user)return res.status(401).json({error:'غير مصرح'});next()};
const owner=(req,res,next)=>{if(req.session.user?.role!=='owner')return res.status(403).json({error:'للمالك فقط'});next()};
app.post('/api/login',(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE username=?').get(req.body.username);if(!u||!bcrypt.compareSync(req.body.password,u.password))return res.status(401).json({error:'بيانات الدخول غير صحيحة'});req.session.user={id:u.id,username:u.username,role:u.role,permissions:JSON.parse(u.permissions||'[]')};res.json(req.session.user)});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/me',(req,res)=>res.json(req.session.user||null));
app.get('/api/dashboard',auth,(req,res)=>{const a=db.prepare('SELECT COUNT(*) c FROM apartments').get().c;const available=db.prepare("SELECT COUNT(*) c FROM apartments WHERE status='متاحة'").get().c;const rented=db.prepare("SELECT COUNT(*) c FROM apartments WHERE status='مؤجرة'").get().c;const maintenance=db.prepare("SELECT COUNT(*) c FROM apartments WHERE status='صيانة'").get().c;const now=new Date();const soon=db.prepare("SELECT * FROM apartments WHERE available_date IS NOT NULL AND date(available_date, '-'||alert_days||' day') <= date(?) AND date(available_date) >= date(?)").all(now.toISOString().slice(0,10),now.toISOString().slice(0,10));const inc=db.prepare("SELECT COALESCE(SUM(amount),0) s FROM finance WHERE type='income'").get().s;const exp=db.prepare("SELECT COALESCE(SUM(amount),0) s FROM finance WHERE type='expense'").get().s;res.json({a,available,rented,maintenance,soon,income:inc,expense:exp,profit:inc-exp});});
app.get('/api/apartments',auth,(req,res)=>res.json(db.prepare('SELECT * FROM apartments ORDER BY created_at DESC').all()));
app.post('/api/apartments',auth,(req,res)=>{const b=req.body,id=uuid();db.prepare('INSERT INTO apartments VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,b.code,b.area,b.neighborhood,b.address,Number(b.rooms||0),Number(b.bathrooms||0),b.living?1:0,b.salon?1:0,b.balcony?1:0,Number(b.space||0),b.floor,b.rent,b.deposit,b.status,b.details,b.available_date||null,Number(b.alert_days||0),new Date().toISOString());res.json({id})});
app.put('/api/apartments/:id',auth,(req,res)=>{const b=req.body;db.prepare('UPDATE apartments SET code=?,area=?,neighborhood=?,address=?,rooms=?,bathrooms=?,living=?,salon=?,balcony=?,space=?,floor=?,rent=?,deposit=?,status=?,details=?,available_date=?,alert_days=? WHERE id=?').run(b.code,b.area,b.neighborhood,b.address,Number(b.rooms||0),Number(b.bathrooms||0),b.living?1:0,b.salon?1:0,b.balcony?1:0,Number(b.space||0),b.floor,b.rent,b.deposit,b.status,b.details,b.available_date||null,Number(b.alert_days||0),req.params.id);res.json({ok:true})});
app.delete('/api/apartments/:id',owner,(req,res)=>{db.prepare('DELETE FROM images WHERE apartment_id=?').run(req.params.id);db.prepare('DELETE FROM apartments WHERE id=?').run(req.params.id);res.json({ok:true})});
app.post('/api/apartments/:id/images',auth,upload.array('images',40),(req,res)=>{for(const f of req.files){db.prepare('INSERT INTO images VALUES (?,?,?,?,?)').run(uuid(),req.params.id,'/uploads/'+path.basename(f.path),f.originalname,new Date().toISOString())}res.json({ok:true,count:req.files.length})});
app.get('/api/apartments/:id/images',auth,(req,res)=>res.json(db.prepare('SELECT * FROM images WHERE apartment_id=?').all(req.params.id)));
app.delete('/api/images/:id',auth,(req,res)=>{db.prepare('DELETE FROM images WHERE id=?').run(req.params.id);res.json({ok:true})});
app.get('/api/tenants',auth,(req,res)=>res.json(db.prepare('SELECT t.*,a.code apartment_code FROM tenants t LEFT JOIN apartments a ON a.id=t.apartment_id ORDER BY t.end_date').all()));
app.post('/api/tenants',auth,(req,res)=>{const b=req.body;db.prepare('INSERT INTO tenants VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(uuid(),b.apartment_id,b.name,b.phone,b.rent,b.start_date,b.end_date,b.deposit,b.renewal||'pending',b.document||'',b.notes||'');res.json({ok:true})});
app.put('/api/tenants/:id',auth,(req,res)=>{const b=req.body;db.prepare('UPDATE tenants SET name=?,phone=?,rent=?,start_date=?,end_date=?,deposit=?,renewal=?,document=?,notes=? WHERE id=?').run(b.name,b.phone,b.rent,b.start_date,b.end_date,b.deposit,b.renewal,b.document,b.notes,req.params.id);res.json({ok:true})});
app.get('/api/finance',auth,(req,res)=>res.json(db.prepare('SELECT * FROM finance ORDER BY date DESC').all()));
app.post('/api/finance',auth,(req,res)=>{const b=req.body;db.prepare('INSERT INTO finance VALUES (?,?,?,?,?,?,?)').run(uuid(),b.type,b.category,b.amount,b.date,b.apartment_id||'',b.notes||'');res.json({ok:true})});
app.get('/api/tasks',auth,(req,res)=>res.json(db.prepare('SELECT * FROM tasks ORDER BY due_date').all()));
app.post('/api/tasks',auth,(req,res)=>{const b=req.body;db.prepare('INSERT INTO tasks VALUES (?,?,?,?,?,?,?)').run(uuid(),b.title,b.details,b.due_date,b.priority,b.assigned_to||'',b.status||'جديدة');res.json({ok:true})});
app.get('/api/admins',owner,(req,res)=>res.json(db.prepare("SELECT id,username,role,permissions FROM users WHERE role='admin'").all().map(x=>({...x,permissions:JSON.parse(x.permissions||'[]')}))));
app.post('/api/admins',owner,(req,res)=>{const b=req.body;db.prepare('INSERT INTO users VALUES (?,?,?,?,?)').run(uuid(),b.username,bcrypt.hashSync(b.password,10),'admin',JSON.stringify(b.permissions||[]));res.json({ok:true})});
app.put('/api/admins/:id',owner,(req,res)=>{const b=req.body;const p=b.password?bcrypt.hashSync(b.password,10):db.prepare('SELECT password FROM users WHERE id=?').get(req.params.id).password;db.prepare('UPDATE users SET username=?,password=?,permissions=? WHERE id=?').run(b.username,p,JSON.stringify(b.permissions||[]),req.params.id);res.json({ok:true})});
app.delete('/api/admins/:id',owner,(req,res)=>{db.prepare('DELETE FROM users WHERE id=? AND role=\'admin\'').run(req.params.id);res.json({ok:true})});
app.use('/uploads',express.static(path.join(__dirname,'uploads')));app.use(express.static(path.join(__dirname,'public')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(process.env.PORT||3000,()=>console.log('West Amman Rentals running'));
