const express=require('express');
const path=require('path');
const app=express();
const PORT=process.env.PORT||10000;
const ROOT=__dirname;
const SUPABASE_URL=(process.env.SUPABASE_URL||'').replace(/\/+$/,'');
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
const OWNER_EMAIL=(process.env.OWNER_EMAIL||'').trim().toLowerCase();
const BUCKET=process.env.SUPABASE_BUCKET||'property-images';
app.disable('x-powered-by');
app.use(express.json({limit:'60mb'}));
app.use(express.urlencoded({extended:true,limit:'60mb'}));
function cfg(){if(!SUPABASE_URL||!SERVICE_KEY)throw new Error('Supabase غير مهيأ.');}
async function sb(p,opt={}){cfg();const r=await fetch(SUPABASE_URL+p,{...opt,headers:{apikey:SERVICE_KEY,Authorization:'Bearer '+SERVICE_KEY,'Content-Type':'application/json',...(opt.headers||{})}});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={message:t}}if(!r.ok){const e=new Error(d?.msg||d?.message||d?.error_description||d?.error||t||`HTTP ${r.status}`);e.status=r.status;e.data=d;throw e}return d}
function bearer(req){const h=String(req.headers.authorization||'');return h.startsWith('Bearer ')?h.slice(7).trim():''}
async function currentUser(req){const token=bearer(req);if(!token)return null;try{const u=await sb('/auth/v1/user',{headers:{Authorization:`Bearer ${token}`}});if(!u?.id)return null;const rows=await sb(`/rest/v1/profiles?id=eq.${encodeURIComponent(u.id)}&select=id,name,email,role,permissions`);const p=rows?.[0];return p&&['owner','admin'].includes(p.role)?{...p,token,authUser:u}:null}catch{return null}}
async function staff(req,res,next){const u=await currentUser(req);if(!u)return res.status(401).json({ok:false,message:'انتهت الجلسة أو الحساب غير مصرح به.'});req.user=u;next()}
async function owner(req,res,next){const u=await currentUser(req);if(!u||u.role!=='owner')return res.status(403).json({ok:false,message:'هذه العملية متاحة للمالك فقط.'});req.user=u;next()}
function mapProp(r){return {id:String(r.client_id||r.id),dbId:r.id,code:r.code,name:r.name,area:r.area,status:r.status,floor:r.floor??'',areaSize:r.area_size??'',price:Number(r.price||0),rooms:Number(r.rooms||0),baths:Number(r.baths||0),balcony:r.balcony?1:0,availabilityDate:r.availability_date||'',contractEnd:r.availability_date||'',alertDays:Number(r.alert_days||7),notes:r.notes||'',video:r.video_url||'',images:Array.isArray(r.images)?r.images:[],tenant:r.tenant||'',phone:r.tenant_phone||''}}
function rowProp(p,images){return {client_id:String(p.id||p.code||Date.now()),code:String(p.code||'').trim(),name:String(p.name||'').trim(),area:String(p.area||'').trim(),status:String(p.status||'متاحة'),floor:p.floor===''||p.floor==null?null:Number(p.floor),area_size:p.areaSize===''||p.areaSize==null?null:Number(p.areaSize),price:Number(p.price||0),rooms:Number(p.rooms||0),baths:Number(p.baths||0),balcony:!!Number(p.balcony||0),availability_date:p.availabilityDate||p.contractEnd||null,alert_days:Number(p.alertDays||7),notes:String(p.notes||''),video_url:String(p.video||''),images:Array.isArray(images)?images.slice(0,10):[],tenant:String(p.tenant||''),tenant_phone:String(p.phone||'')}}
function dataImage(s){const m=String(s||'').match(/^data:(image\/(?:jpeg|png|webp));base64,(.+)$/);return m?{type:m[1],buf:Buffer.from(m[2],'base64')}:null}
async function storeImages(images,userId){const out=[];for(let i=0;i<Math.min(10,(images||[]).length);i++){const x=String(images[i]||'');if(!x)continue;if(!x.startsWith('data:')){out.push(x);continue}const d=dataImage(x);if(!d)continue;const ext=d.type==='image/png'?'png':d.type==='image/webp'?'webp':'jpg';const objectPath=`properties/${encodeURIComponent(String(userId||'staff'))}/${Date.now()}-${Math.random().toString(36).slice(2,9)}-${i}.${ext}`;const r=await fetch(`${SUPABASE_URL}/storage/v1/object/${encodeURI(BUCKET)}/${objectPath}`,{method:'POST',headers:{apikey:SERVICE_KEY,Authorization:`Bearer ${SERVICE_KEY}`,'Content-Type':d.type,'x-upsert':'true'},body:d.buf});const t=await r.text();if(!r.ok)throw new Error(t||'فشل رفع الصورة');out.push(`${SUPABASE_URL}/storage/v1/object/public/${encodeURI(BUCKET)}/${objectPath}`)}return out}

app.post('/api/login',async(req,res)=>{try{const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||'');if(!email||!password)return res.status(400).json({ok:false,message:'أدخل البريد الإلكتروني وكلمة المرور.'});const a=await sb('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});const id=a?.user?.id;if(!id)return res.status(401).json({ok:false,message:'بيانات الدخول غير صحيحة.'});let rows=await sb(`/rest/v1/profiles?id=eq.${encodeURIComponent(id)}&select=id,name,email,role,permissions`);let p=rows?.[0];
if(!p){
  const byEmail=await sb(`/rest/v1/profiles?email=eq.${encodeURIComponent(email)}&select=id,name,email,role,permissions&limit=1`).catch(()=>[]);
  p=byEmail?.[0];
  if(!p){
    const all=await sb('/rest/v1/profiles?select=id&limit=1');
    if(all?.length && email!==OWNER_EMAIL)return res.status(403).json({ok:false,message:'هذا الحساب غير مصرح به.'});
    const ins=await sb('/rest/v1/profiles',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({id,name:a.user.user_metadata?.name||'المالك',email,role:'owner',permissions:['dashboard','properties','tenants','reports','settings','admins','messages']})});
    p=ins?.[0];
  }
}
if(!p||!['owner','admin'].includes(p.role))return res.status(403).json({ok:false,message:'هذا الحساب غير مصرح به.'});await sb('/rest/v1/login_logs',{method:'POST',body:JSON.stringify({user_id:id,email,success:true})}).catch(()=>{});res.json({ok:true,token:a.access_token,user:{id:p.id,name:p.name||email,email:p.email||email,role:p.role,permissions:p.permissions||[]}})}catch(e){res.status(e.status===400||e.status===401?401:500).json({ok:false,message:e.message||'تعذر تسجيل الدخول.'})}});
app.post('/api/logout',staff,(req,res)=>res.json({ok:true}));

app.get('/api/public/properties',async(req,res)=>{try{const rows=await sb('/rest/v1/properties?select=*&order=created_at.desc');if(rows?.length)return res.json(rows.map(mapProp));const st=await sb("/rest/v1/app_state?id=eq.global&select=data");res.json(Array.isArray(st?.[0]?.data?.properties)?st[0].data.properties:[])}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/properties',staff,async(req,res)=>{try{const rows=await sb('/rest/v1/properties?select=*&order=created_at.desc');res.json((rows||[]).map(mapProp))}catch(e){res.status(500).json({error:e.message})}});

async function upsertProp(p,userId){const images=await storeImages(p.images||[],userId);const row=rowProp(p,images);let existing=await sb(`/rest/v1/properties?client_id=eq.${encodeURIComponent(row.client_id)}&select=id`);let out;if(existing?.[0]?.id){out=await sb(`/rest/v1/properties?id=eq.${existing[0].id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(row)})}else{out=await sb('/rest/v1/properties',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)})}return mapProp(out?.[0]||row)}
app.post('/api/properties',staff,async(req,res)=>{try{const p=await upsertProp(req.body||{},req.user.id);res.json(p)}catch(e){res.status(e.status||500).json({error:e.message||'تعذر حفظ الشقة.'})}});
app.put('/api/properties/:id',staff,async(req,res)=>{try{const p={...(req.body||{}),id:req.params.id};const out=await upsertProp(p,req.user.id);res.json(out)}catch(e){res.status(e.status||500).json({error:e.message||'تعذر تعديل الشقة.'})}});
app.delete('/api/properties/:id',staff,async(req,res)=>{try{await sb(`/rest/v1/properties?client_id=eq.${encodeURIComponent(req.params.id)}`,{method:'DELETE'});res.json({ok:true})}catch(e){res.status(e.status||500).json({error:e.message})}});

app.get('/api/users',staff,async(req,res)=>{try{res.json(await sb('/rest/v1/profiles?select=id,name,email,role,permissions&order=created_at.asc'))}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/users',owner,async(req,res)=>{try{const name=String(req.body?.name||'').trim(),email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||'');if(!name||!email||password.length<6)return res.status(400).json({error:'أكمل الاسم والبريد وكلمة المرور (6 أحرف على الأقل).'});const created=await sb('/auth/v1/admin/users',{method:'POST',body:JSON.stringify({email,password,email_confirm:true,user_metadata:{name}})});const id=created?.id||created?.user?.id;if(!id)throw Error('تعذر إنشاء حساب المدير.');const permissions=(Array.isArray(req.body.permissions)?req.body.permissions:[]).filter(x=>['dashboard','properties','tenants','reports','settings','admins','messages'].includes(x));const ins=await sb('/rest/v1/profiles',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({id,name,email,role:'admin',permissions})});res.json({ok:true,user:ins?.[0]})}catch(e){res.status(e.status===422?409:(e.status||500)).json({error:e.status===422?'البريد مستخدم بالفعل.':e.message})}});
app.put('/api/users/:id',owner,async(req,res)=>{try{const id=encodeURIComponent(req.params.id),b=req.body||{};const profile=(await sb(`/rest/v1/profiles?id=eq.${id}&select=*`))?.[0];if(!profile)return res.status(404).json({error:'المستخدم غير موجود.'});if(profile.role==='owner'&&req.user.id!==profile.id)return res.status(403).json({error:'لا يمكن تعديل مالك آخر.'});const fields={name:String(b.name||profile.name),email:String(b.email||profile.email).toLowerCase(),permissions:Array.isArray(b.permissions)?b.permissions:profile.permissions};const up=await sb(`/rest/v1/profiles?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(fields)});if(b.password){if(String(b.password).length<6)return res.status(400).json({error:'كلمة المرور يجب أن تكون 6 أحرف أو أكثر.'});await sb(`/auth/v1/admin/users/${id}`,{method:'PUT',body:JSON.stringify({password:String(b.password),user_metadata:{name:fields.name}})})}res.json({ok:true,user:up?.[0]||{...profile,...fields}})}catch(e){res.status(e.status||500).json({error:e.message})}});
app.post('/api/admin/create',owner,async(req,res)=>{req.body={...req.body,permissions:req.body?.permissions||['dashboard','properties']};const fake={body:req.body,user:req.user};try{const name=String(fake.body.name||'').trim(),email=String(fake.body.email||'').trim().toLowerCase(),password=String(fake.body.password||'');const created=await sb('/auth/v1/admin/users',{method:'POST',body:JSON.stringify({email,password,email_confirm:true,user_metadata:{name}})});const id=created?.id||created?.user?.id;const permissions=fake.body.permissions.filter(x=>['dashboard','properties','tenants','reports','settings','admins','messages'].includes(x));const ins=await sb('/rest/v1/profiles',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({id,name,email,role:'admin',permissions})});res.json({ok:true,user:ins?.[0]})}catch(e){res.status(e.status||500).json({ok:false,message:e.message})}});

app.get('/api/state',staff,async(req,res)=>{try{const rows=await sb('/rest/v1/app_state?id=eq.global&select=data');res.json({ok:true,state:rows?.[0]?.data||null})}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/state',staff,async(req,res)=>{try{const b=req.body||{};let props=[];for(const p of (Array.isArray(b.properties)?b.properties:[])){props.push(await upsertProp(p,req.user.id))}const payload={tenants:Array.isArray(b.tenants)?b.tenants:[],settings:b.settings||{},searchHistory:Array.isArray(b.searchHistory)?b.searchHistory.slice(0,50):[],design:b.design||'design1',chat:Array.isArray(b.chat)?b.chat.slice(-200):[]};const body={id:'global',data:payload,updated_by:req.user.id};await sb('/rest/v1/app_state?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(body)});res.json({ok:true,properties:props,state:payload})}catch(e){console.error('STATE_SAVE',e);res.status(e.status||500).json({error:e.message||'تعذر حفظ البيانات.'})}});

app.get('/api/health',async(req,res)=>res.json({ok:true,service:'west-amman-property-manager',version:'FINAL-ORIGINAL-DESIGN-SUPABASE',supabaseConfigured:!!(SUPABASE_URL&&SERVICE_KEY)}));
app.use(express.static(ROOT,{index:'index.html',extensions:['html']}));
app.get('*splat',(req,res)=>res.sendFile(path.join(ROOT,'index.html')));
app.listen(PORT,'0.0.0.0',()=>console.log(`West Amman Property Manager running on ${PORT}`));
