-- WEST AMMAN PROPERTY MANAGER FINAL 19.0
create extension if not exists pgcrypto;

create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 name text not null default '',
 email text not null default '',
 role text not null check(role in('owner','admin')),
 permissions text[] not null default array['dashboard','properties','tenants','contracts','reports','settings','messages'],
 created_at timestamptz not null default now()
);

create table if not exists public.properties(
 id bigint generated by default as identity primary key,
 code text not null unique,
 name text not null,
 area text not null,
 status text not null default 'متاحة',
 floor numeric,
 area_size numeric,
 price numeric not null default 0,
 rooms integer not null default 0,
 baths integer not null default 0,
 balcony boolean not null default false,
 availability_date date,
 notes text not null default '',
 video_url text not null default '',
 images text[] not null default '{}',
 created_at timestamptz not null default now()
);

create table if not exists public.app_state(
 key text primary key,
 data jsonb not null default '{}'::jsonb
);


create table if not exists public.tenants(
 id bigint generated by default as identity primary key,
 name text not null,
 phone text not null default '',
 property_code text not null default '',
 notes text not null default '',
 created_at timestamptz not null default now()
);
create table if not exists public.contracts(
 id bigint generated by default as identity primary key,
 property_code text not null default '',
 tenant_name text not null default '',
 start_date date,
 end_date date,
 amount numeric not null default 0,
 created_at timestamptz not null default now()
);
alter table public.tenants enable row level security;
alter table public.contracts enable row level security;

create table if not exists public.messages(
 id bigint generated by default as identity primary key,
 sender_id uuid references auth.users(id) on delete set null,
 message text not null default '',
 created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.properties enable row level security;
alter table public.app_state enable row level security;
alter table public.messages enable row level security;

drop policy if exists "public read properties" on public.properties;
create policy "public read properties" on public.properties for select using(true);

insert into public.app_state(key,data)
values('main',jsonb_build_object(
 'areas',jsonb_build_array('عبدون','أم أذينة','الرابية','خلدا','دير غبار','دابوق','الصويفية','وادي السير','بيادر وادي السير','أم السماق','تلاع العلي','الشميساني','جبل عمان','العبدلي','مرج الحمام','شارع مكة','الدوار الأول','الدوار الثاني','الدوار الثالث','الدوار الرابع','الدوار الخامس','الدوار السادس'),
 'alertDays',7
))
on conflict(key) do nothing;

insert into storage.buckets(id,name,public)
values('property-images','property-images',true)
on conflict(id) do update set public=true;

-- لا تعطِ المتصفح مفتاح Service Role.
-- ضع SUPABASE_URL و SUPABASE_SERVICE_ROLE_KEY في Render Environment.
