-- عقارات غرب عمان v16
-- الصق هذا الملف كاملاً في Supabase SQL Editor ثم نفّذه.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  email text not null default '',
  role text not null check (role in ('owner','admin')),
  permissions text[] not null default array['dashboard','properties','tenants','reports','settings','messages'],
  created_at timestamptz not null default now()
);

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  area text not null,
  status text not null default 'متاحة',
  floor numeric,
  area_size numeric,
  price numeric not null default 0,
  rooms integer not null default 0,
  baths integer not null default 0,
  balcony boolean not null default false,
  availability_date date,
  notes text not null default '',
  video_url text not null default '',
  images text[] not null default '{}',
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.properties enable row level security;

drop policy if exists "public read properties" on public.properties;
create policy "public read properties" on public.properties for select using (true);

-- الإدارة تتم بواسطة server.js باستخدام Service Role Key.
-- لذلك لا نعطي المتصفح صلاحيات كتابة مباشرة.

insert into storage.buckets (id,name,public)
values ('property-images','property-images',true)
on conflict (id) do update set public=true;

-- ملاحظة: حسابات المالك والمدير ينشئها التطبيق تلقائياً عند أول تشغيل
-- إذا أضفت متغيرات BOOTSTRAP_OWNER_EMAIL / BOOTSTRAP_OWNER_PASSWORD
-- و BOOTSTRAP_ADMIN_EMAIL / BOOTSTRAP_ADMIN_PASSWORD في Render.
