create extension if not exists pgcrypto;

create table if not exists public.profiles(
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  email text not null default '',
  role text not null check(role in ('owner','admin')),
  permissions text[] not null default array['dashboard','properties','tenants','reports','settings','messages'],
  created_at timestamptz not null default now()
);

create table if not exists public.properties(
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  area text not null,
  status text not null default 'متاحة',
  floor numeric,
  area_size numeric,
  price numeric not null default 0,
  rooms integer not null default 0,
  baths integer not null default 0,
  balcony boolean not null default false,
  availability_date date,
  alert_days integer not null default 7,
  notes text not null default '',
  video_url text not null default '',
  images text[] not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists public.app_state(
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.properties enable row level security;
alter table public.app_state enable row level security;

drop policy if exists "public read properties" on public.properties;
create policy "public read properties" on public.properties for select using(true);

insert into storage.buckets(id,name,public) values('property-images','property-images',true)
on conflict(id) do update set public=true;

-- إصلاحات التوافق للنسخ السابقة
alter table public.properties add column if not exists alert_days integer not null default 7;
